### ISSUE TITLE
Release 1.9R0, html command "infos" generate reboot

### ISSUE THREAD

**Issue by warohas** [karawin/Ka-Radio32#100]
everytime when command infos is called - system reboot, but answer is send e.g.
vol: 104
num: 1
stn: Hitradio OE3
tit: HITRADIO Ã–3 - Nachrichten, Wetter und Verkehr
sts: 1
other commands are workig correctly like play, stop, volume

**Comment by karawin** [comment]
Thanks for the issue, but it is for KaRadio and not KaRadio32.
For KaRadio, please update again. It will works now.
