### ISSUE TITLE
Feature to delay power to amplifier 

### ISSUE THREAD

**Issue by stpavel** [karawin/Ka-Radio32#101]
When karadio turn on and initialize the VS1053, the speaker can hear the background and two unpleasant clicks. After initialization everything is OK. the Idea is to use one GPIO to activate the relay with a delay. For example, supply power to the amplifier after 5 seconds when VS1053 initialization is finished.

**Comment by karawin** [comment]
No need a gpio. Just a delay (rc) for your relay.
