### ISSUE TITLE
Unable to enter any text in the web-interface. 1.9R2

### ISSUE THREAD

**Issue by X-Stas-EEE** [karawin/Ka-Radio32#103]
Steps to reproduce:

1. Flash the 1.9R2
2. Go to the web-interface
3. Try to enter any text into any input field

Actual result:
Input by keyboard doesn't work. Only Copy/Paste way is available

Expected result:
All the enabled text fields must be available for input as it is in 1.8

**Comment by karawin** [comment]
Yes, sorry a  mistake. Corrected now.
Thanks

**Comment by X-Stas-EEE** [comment]
Reviewed and CLOSED

**Comment by karawin** [comment]
Another bug corrected. Please update again.
