### ISSUE TITLE
Open wifi

### ISSUE THREAD

**Issue by nano111** [karawin/Ka-Radio32#108]
Hi,
I do not know if it is a feature or bug,but my karadio32 on Lilygo TM ESP32 board cannot connect to wifi  network that does not have encription,network that  is open  to connect without password.
If I leave password empty and put just ssid, it imedietly goes to ap mode.

**Comment by karawin** [comment]
Yes, a too strict control.
			if  (strlen(ssid)&&strlen(pass))
to changed to 
			if  (strlen(ssid))
in next release. or try the prerelease
sys.prerelease

**Comment by nano111** [comment]
It works,thanks
