### ISSUE TITLE
3 button interface description/example

### ISSUE THREAD

**Issue by diver321** [karawin/Ka-Radio32#109]
Can please someone post a schema and describe how to connect (which pins and maybe resistors if needed... ) 3 button control interface (button switches keyboard) to ESP32 board - which is defined in gpio config? As an example.
What i need is control (previous station button), (play/pause button), (next station button) - nothing more.
Ist that even possible with this 3 button interface? How can define which button - which function?
Is there somewhere a description? Thank You.
BTW - great project.

**Comment by karawin** [comment]
see https://github.com/karawin/Ka-Radio32/blob/master/HardwareConfig.md
Buttons
Two set of three buttons can be configured in place or with encoder(s). The only limit is the available gpio's.
Each set has functions equivalent to Encoder0 and Encoder1:
click on button A: Start/Stop playing
click on button B and C: volume down and up for set 0 (P_BTN0), Station down and up for set 1 (P_BTN1)
held on button A: click on button B and C: volume down and up for set 1 (P_BTN1), Station down and up for set 0 (P_BTN0)
A button may be active with a level of 0 volt (0) (default) or +3.3volt (1)

If a set is not used, P_BTNx_A must be set to 255. In this case P_BTNx_B P_BTNx_C are disabled too.


![switch](https://user-images.githubusercontent.com/7613191/55947680-3b629900-5c4f-11e9-8ceb-07fa8cb81cb4.jpg)
