### ISSUE TITLE
wifi.discon not work

### ISSUE THREAD

**Issue by marcinmaster999** [karawin/Ka-Radio32#11]
Command wifi.discon only reconnect connection and print message  WIFI.DISCONNECT FAILED

**Comment by karawin** [comment]
Yes true. I forgot that the disconnect event try to connect again in case of disconnection.
Is it usefull?

**Comment by marcinmaster999** [comment]
Yes. Maybe can add the wifi.reconnect command and remain wifi.discon normally to disconnect

**Comment by karawin** [comment]
done in next release.
with a new command
wifi.recon to reconnect manually.

**Comment by karawin** [comment]
Done
