### ISSUE TITLE
32bit I2S DACs not handled correctly

### ISSUE THREAD

**Issue by har-in-air** [karawin/Ka-Radio32#111]
In audio_renderer.c : render_samples() function, for a 32bit output stream, outBuf8 needs to be malloc'ed with double the size of the input buffer, not the same size, as for every 16bit sample, there is a 16bit zero padding.

As the code stands, it will cause a memory fault on selecting I2S_MERIUS (32bits) when playing a stream.

I've fixed this and its working fine now with my homebrew I2S power amplifier using TAS5753MD chip (which requires a 32bit input stream for other reasons).

++
	uint32_t outBufBytes = buf_len*(2/buf_desc->num_channels);
       if (renderer_instance->bit_depth == I2S_BITS_PER_SAMPLE_32BIT) outBufBytes <<= 1;
	outBuf8 = malloc(outBufBytes);
++
and at the end of the function you need the same  fix 
++++
 size_t bytes_left = outBufBytes;
    size_t bytes_written = 0;
    while(bytes_left > 0 && renderer_status != STOPPED) {
        res = i2s_write(renderer_instance->i2s_num, (const char*) outBuf8, bytes_left,& bytes_written, max_wait);
		if (res != ESP_OK) {
			ESP_LOGE(TAG, "i2s_write error %d",res);
			}
	if (bytes_written != bytesLeft) ESP_LOGV(TAG, "written: %d, len: %d",bytes_written,bytes_left);
   
++++

**Comment by karawin** [comment]
Ok, thanks

**Comment by karawin** [comment]
if (bytes_written != bytes_left) ESP_LOGV(TAG, "written: %d, len: %d",bytes_written,bytes_left);
