### ISSUE TITLE
Crash if lcd.type is 255

### ISSUE THREAD

**Issue by pilnikov** [karawin/Ka-Radio32#115]
Hello JP. I have problem again

Part of Config file

![conf](https://user-images.githubusercontent.com/25922873/57124181-31d7d700-6d9e-11e9-92ce-b875096b223a.JPG)
 
Result

![vs_only1](https://user-images.githubusercontent.com/25922873/57124103-dad20200-6d9d-11e9-9232-6f524bab226a.JPG)

Switch from 192 to 255

![vs_only3](https://user-images.githubusercontent.com/25922873/57124413-305ade80-6d9f-11e9-8bdc-8e439c10a6d0.JPG)

I suggest to do a preliminary analysis of the config file and form several flags according to its results.
Example: O_LCD_TYPE, data, u8,255 -> Display is "Not used" -> a ban on launching all the blocks responsible for initializing the display and outputting information to it.
Example2: The default audio output type is I2S, but in configuration:
P_I2S_LRCK, data, u8,255
P_I2S_BCLK, data, u8,255
P_I2S_DATA, data, u8,255
The system will start swearing at the wrong configuration of the GPIO -> if I2S is prohibited in the config file - do not start its handler. By analogy, you can do with handlers of buttons,  joysticks, encoders and IR
tnx

**Comment by karawin** [comment]
Yes. A problem.
update again. It works now.
A complete correction soon.

**Comment by karawin** [comment]
Ok in R4
