### ISSUE TITLE
WiFi password length

### ISSUE THREAD

**Issue by alexandertischenko** [karawin/Ka-Radio32#124]
After setting up the network through the AP mode, the device reboots and works normally. But in the settings menu, the "AP SSID:" and "AP PASSWORD:" all fields become empty. Perhaps the reason for this is the length of my wifi password of 17 characters?

**Comment by karawin** [comment]
Please update again even if it is the same.
Some time ago i made a little change in this part of code.
NB: the password is 64 chars length.

**Comment by alexandertischenko** [comment]
SSID and password is not displayed anyway. Probably the whole problem is in the special characters of my wireless password: «Gerri?hoEW<AP"0_»?

**Comment by karawin** [comment]
Yes, the " is the problem. I will modify the code soon. Thanks

**Comment by alexandertischenko** [comment]
After installing 1.9R5 WiFi password with character “ shows into the web interface AP PASSWORD field, but esp32 can’t connect with WiFi router and creates access point by default.

**Comment by karawin** [comment]
Yes sorry a mistake.
Update again.

**Comment by alexandertischenko** [comment]
Works fine. Thanks!
