### ISSUE TITLE
Wrong time zone

### ISSUE THREAD

**Issue by Valenttt** [karawin/Ka-Radio32#126]
Hi,
When setting the time zone +10 time is displayed incorrectly, it adds 1 hour.
There is no transfer of hours for summer time in Russia.

**Comment by karawin** [comment]
The NTP server likewise has no knowledge of daylight saving time.

**Comment by Valenttt** [comment]
I am now setting a time zone of +9 to get a time zone of +10, 
I hope the bug will be fixed.

**Comment by Valenttt** [comment]
For comparison https://www.timeserver.ru/cities/ru/vladivostok

**Comment by karawin** [comment]
The time zone is used to adjust the date and time with respect to universal time. An NTP server does not have the knowledge of summer hours. He does not know the Daylight Savings Time.
It is not a bug but a feature ;-).
May be this information can be found elsewhere on internet but I had not written such a code.

**Comment by Valenttt** [comment]
ok
