### ISSUE TITLE
LCD backlight

### ISSUE THREAD

**Issue by Valenttt** [karawin/Ka-Radio32#128]
Hi, I can’t implement the scheme for automatically turning off the backlight of the LCD display via sys.lcdout ("30"). 

![lcd](https://user-images.githubusercontent.com/45222413/61029875-6d76c900-a3ff-11e9-8efd-a1967896e162.jpg). 

In the file pattern.csv, GPIO22 cleaned and applied it for highlighting.

P_I2S_DATA, data, u8,255
P_BACKLIGHT, data, u8,22

then made pattern.bin, flashed to the address 0x3a2000. After the overload, the backlight turned on, but after 30 seconds. does not turn off.

Tell me what I'm doing wrong?

**Comment by pilnikov** [comment]
Try this schematic diagram
![image](https://user-images.githubusercontent.com/25922873/61034693-28429f00-a3df-11e9-9fb6-5d4cdbe24c7d.png)
102R = 1KOhm
103R = 10kOhm
Q1 - any n- channel mosfet, e.g. 2N7002

**Comment by pilnikov** [comment]
в исходной схеме неверно включен полевик - он всегда открыт через паразитный диод, который есть физически, но на схеме не указан.
