### ISSUE TITLE
Stop and sleep lcd.

### ISSUE THREAD

**Issue by Valenttt** [karawin/Ka-Radio32#130]
Hi, need a simple function so that after some time after pressing the “Stop” button, the lcd is turned off, for example, sys.sleeplcd (“120”), but during playback, lcd is not turned off. 

The sys.lcdout function (“254”) turns off the screen every 4 minutes.

I hope to see this function in the future firmware.

**Comment by karawin** [comment]
sys.lcdout("x")	: Timer in seconds to switch off the lcd. 0= no timer
I will think about a solution. Thanks

**Comment by karawin** [comment]
Working on a sys.lcdstop command.

**Comment by karawin** [comment]
Done in R7
