### ISSUE TITLE
Error when change the station

### ISSUE THREAD

**Issue by florin2520** [karawin/Ka-Radio32#137]
Please help. When I start the radio, it play well but when I change the station it stop and the web interface become unresponsive.
![error](https://user-images.githubusercontent.com/15236097/66258948-f9f11780-e7b3-11e9-8d56-1d0ee49f1d82.png)

![Capture2](https://user-images.githubusercontent.com/15236097/66259071-82bc8300-e7b5-11e9-86fb-97692f24e1e8.JPG)

**Comment by karawin** [comment]
RMT RX is the IR receiver. Something wrong around it.

**Comment by florin2520** [comment]
> RMT RX is the IR receiver. Something wrong around it.

A bad connection. Solved. Thank you!
