### ISSUE TITLE
Direction of Encoder turn was changed

### ISSUE THREAD

**Issue by Sera26** [karawin/Ka-Radio32#139]
Hello,

Direction of encoder function was changed due to unknown reason. Volume is decreasing in clockwise, increasing in anticlockwise. Why?

**Comment by pilnikov** [comment]
a
b
     c
d
     e

"a c e" - encoders, "b d" knob (switch). Please swap the a <-> c .

**Comment by Sera26** [comment]
Hello My Friend,

So I have CLK, DT, SW, VCC and GND pin on encoder. You mean I need to swap CLK and GND?

**Comment by pilnikov** [comment]
#define PIN_ENC0_A   GPIO_NUM_16	//16	// 255 if encoder not used
#define PIN_ENC0_B   GPIO_NUM_17	//17	// DT
#define PIN_ENC0_BTN GPIO_NUM_5		//5// SW
A&B

**Comment by Sera26** [comment]
It works! Many thanks for help my Friend.
