### ISSUE TITLE
New feature suggestion : Touch control of Ka Radio 32

### ISSUE THREAD

**Issue by gerardwr** [karawin/Ka-Radio32#16]
This is a suggestion for an additional feature to use the ESP32 "touch" feature in Ka Radio 32.

Now that I have attached an Oled display to my KaRadio-32 I think it would be great to control Karadio without using the webpage.

The use of the “ESP32 touch” feature to control Karadio32 would be a nice addition, ref:
http://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/touch_pad.html

I have seen an addon with mechanical microswitches  for controls (the ESP8266 version?) so maybe the basic code is in place and adding touch control is not too complicated.

Looking at my Oled SSD1306 display the use of the metallic islands of the mounting holes would make excellent touch-controls. As far as I can see the islands are not connected to the rest of the PCB. It would require:
- 4 additional wires from the mounting holes to the ESP32 touch GPIO's
- and ofcourse software changes

![karadio ssd1306 touch](https://user-images.githubusercontent.com/10114857/34692381-3db7ee00-f4c0-11e7-895d-2e85474e0ed6.png)

**Comment by karawin** [comment]
Hemm... buy a ky040 rotary encoder. Much more easy and a full control in one.

**Comment by gerardwr** [comment]
Ok, I understand.

But I must say I like the very simple basic setup with just the ESP32 and the Oled and no extra hardware like an external DAC, external decoder, etc.

Not a real problem for me, In practice I always listen to the Frech Morow Radio station :-)

**Comment by karawin** [comment]
Play/Stop        Volume/Station

vol/station -    vol/station +

Is better no?
Interesting project but not generic
So I will not do it because of the lack of available gpio

**Comment by gerardwr** [comment]
Yes, your suggestion for buttons is beter.

I understand your reason for not implementing it. no hard feelings.

Thx for the great software, Closing this issue now.
