### ISSUE TITLE
Release 1.9 Rev 7 

### ISSUE THREAD

**Issue by tototek** [karawin/Ka-Radio32#164]
As of updating to 1.9 R7, the screen display went black, it was working perfectly with version 1.9 R6.
How do I normalize it again? The web interface works OK.
Marcelo

**Comment by karawin** [comment]
sys.lcd("xxx")

Just gives again the lcd type.
I noticed that sometime with this release, it happens. Don't know why.

**Comment by tototek** [comment]
OK with sys.lcd("192").Thank you.
