### ISSUE TITLE
vs1053 noise (solution)

### ISSUE THREAD

**Issue by rolandinchania** [karawin/Ka-Radio32#167]
Browsing the internet I found a solution to remove noise  and ground loop audio problems when useing the vs1053 dac board with an external audio amplifier. 

https://electronics.stackexchange.com/a/186921

important: the wireing diagram at the and of the article. Don't use the GBUF signal as ground with an external amp because its for the headphone output. Use  GND instead.

Big success for my project. !!!

**Comment by karawin** [comment]
Yes or simply a couple of isolation transformers.

**Comment by rolandinchania** [comment]
Thanks. I made 2 simple changes to my vs1053 board. 
1. cut the gbuf line
2. add new groundwire (black)

![vs1053](https://user-images.githubusercontent.com/51438058/75093587-bc86fe00-558b-11ea-8e03-a74a2b899d80.jpg)

**Comment by cheise** [comment]
I would have the same problem, thanks for this solution. 

cu

**Comment by rolandinchania** [comment]
Thank you, it's cool !!!

**Comment by rolandinchania** [comment]
Thank you all.

**Comment by Sera26** [comment]
Hello,

I really like your solution and want to perform it.
But I have the red version of VS1053 board.
Could you help me which lines need to be cutted and bridged?
Thank you in advance.

![vs1053](https://user-images.githubusercontent.com/46669666/112975288-bcc0d800-9153-11eb-8d68-f75bfd41c2e3.png)

**Comment by rolandinchania** [comment]
Hi,

I don't know the board but similar to the green board I suggest:

Cut where the little black line is. then connect from the connector to ground.

for example ground is under the green dot when you remove the paint on the board.

Regards Roland

 

ps. I enclosed a picture

**Comment by Sera26** [comment]
Hi,

Thanks for quick response.
If I well understand...need to cut line of the current gnd of speaker jack and bridged to main GND of the board (your dots)?

**Comment by rolandinchania** [comment]
exactly 😊-- Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.Am 30.03.21, 20:01 schrieb Sera26 ***@***.***>:

   
  Hi, 
  Thanks for quick response. If I well understand...need to cut line of the current gnd of speaker jack and bridged to main GND of the board (your dots)?

**Comment by Sera26** [comment]
No problem :) Thank you for support :)

**Comment by cheise** [comment]
![vs1053](https://user-images.githubusercontent.com/59045759/113108326-28af4900-9205-11eb-9bf3-3a606ef595a6.png)

;)

**Comment by Sera26** [comment]
Yes, it is, thank you very much :)
