### ISSUE TITLE
Screensaver to prevent OLED burnout.

### ISSUE THREAD

**Issue by evilslon** [karawin/Ka-Radio32#169]
Hello! 
I use a monochrome OLED display in my KaRadio32, but there's one problem - the display burns out when the device is in sleep mode (when it shows the clock). Could you make something similar to a screensaver (for example, for clock numbers changing the position on the screen) to prevent pixels from burning out? That would be great!

Thank you for your excellent work!

![IMG_8575](https://user-images.githubusercontent.com/13298616/75328927-d37d6700-588f-11ea-9948-4725f2181380.JPG)
![IMG_8577](https://user-images.githubusercontent.com/13298616/75328935-d5dfc100-588f-11ea-926a-4a50e78dd251.JPG)

**Comment by hjgode** [comment]
I also need some help to make oled display either dim or mover around, when stopped playing. Some kind of screen off or screen saver would be good.

**Comment by hjgode** [comment]
In the meantime I will use the command 
          sys.lcdstop("5") 
to shutdown the OLED after 5 seconds when I stopped playing. There is also an option to make the display go off in play/normal mode: 
          sys.lcdout("10") 
will switch off the display in play mode after 10 seconds of being idle.

Oled displays support a contrast settings, that may be usefull to 'dim' the display after some idle time. But this would require some extra coding...
