### ISSUE TITLE
Compilation error with esp-idf-v4.0.1

### ISSUE THREAD

**Issue by balsub123** [karawin/Ka-Radio32#181]
Dear Karawin,

I have two issues.

1- Not able to compile KaRadio32 - version 1.9.7 with esp-idf-v4.0.1. 

C:\esp-idf-v4.0.1\examples\Ka-Radio32-master>idf.py build
Checking Python dependencies...
Python requirements from C:\esp-idf-v4.0.1\requirements.txt are satisfied.
Executing action: all (aliases: build)
Running ninja in directory c:\esp-idf-v4.0.1\examples\ka-radio32-master\build
Executing "ninja all"...
[1/686] cmd.exe /C "cd /D C:\esp-idf-v4.0.1\examples\Ka-Ra...*********************************************************"
Partition table binary generated. Contents:
*******************************************************************************
# Espressif ESP32 Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,16K,
otadata,data,ota,0xd000,8K,
phy_init,data,phy,0xf000,4K,
ota_0,app,ota_0,0x10000,1792K,
ota_1,app,ota_1,0x1d0000,1792K,
device,64,0,0x390000,4K,
stations,65,0,0x391000,64K,
device1,66,0,0x3a1000,4K,
hardware,data,nvs,0x3a2000,12K,
*******************************************************************************
[2/686] Building C object esp-idf/app_update/CMakeFiles/__idf_app_update.dir/esp_app_desc.c.obj
FAILED: esp-idf/app_update/CMakeFiles/__idf_app_update.dir/esp_app_desc.c.obj
ccache C:\.espressif\tools\xtensa-esp32-elf\esp-2019r2-8.2.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -D PROJECT_NAME=\"Ka-Radio32-master\" -DPROJECT_VER=\"\"1.9.7\"\" -Iconfig -I../../../components/app_update/include -I../../../components/newlib/platform_include -I../../../components/freertos/include -I../../../components/heap/include -I../../../components/log/include -I../../../components/soc/esp32/include -I../../../components/soc/include -I../../../components/esp_rom/include -I../../../components/esp_common/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/esp32/include -I../../../components/driver/include -I../../../components/esp_ringbuf/include -I../../../components/esp_event/include -I../../../components/tcpip_adapter/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_wifi/esp32/include -I../../../components/esp_eth/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/app_trace/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -nostdlib -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fstack-protector -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.0.1-dirty\" -DGCC_NOT_5_2_0 -DESP_PLATFORM -MD -MT esp-idf/app_update/CMakeFiles/__idf_app_update.dir/esp_app_desc.c.obj -MF esp-idf\app_update\CMakeFiles\__idf_app_update.dir\esp_app_desc.c.obj.d -o esp-idf/app_update/CMakeFiles/__idf_app_update.dir/esp_app_desc.c.obj -c C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c
<command-line>: error: too many decimal points in number
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:27:16: note: in expansion of macro 'PROJECT_VER'
.version = PROJECT_VER,
^~~~~~~~~~~
<command-line>: error: expected '}' before numeric constant
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:27:16: note: in expansion of macro 'PROJECT_VER'
.version = PROJECT_VER,
^~~~~~~~~~~
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:22:78: note: to match this '{'
const __attribute__((section(".rodata_desc"))) esp_app_desc_t esp_app_desc = {
^
<command-line>: error: too many decimal points in number
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:54:23: note: in expansion of macro 'PROJECT_VER'
_Static_assert(sizeof(PROJECT_VER) <= sizeof(esp_app_desc.version), "PROJECT_VER is longer than version field in structure");
^~~~~~~~~~~
<command-line>: error: expected ')' before numeric constant
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:54:23: note: in expansion of macro 'PROJECT_VER'
_Static_assert(sizeof(PROJECT_VER) <= sizeof(esp_app_desc.version), "PROJECT_VER is longer than version field in structure");
^~~~~~~~~~~
C:/esp-idf-v4.0.1/components/app_update/esp_app_desc.c:54:22: note: to match this '('
_Static_assert(sizeof(PROJECT_VER) <= sizeof(esp_app_desc.version), "PROJECT_VER is longer than version field in structure");
^
[11/686] Building CXX object esp-idf/nvs_flash/CMakeFiles/__idf_nvs_flash.dir/src/nvs_storage.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

2) But if I exclude PROJECT_VER from firmware image                                                │ │     │ │                   and  PROJECT_NAME from firmware image, it's able to compile it but I get the following error :

C:/esp-idf-v4.0.1/components/esp32/cpu_start.c:537: undefined reference to `app_main'

How to solve these problems? Any clue or solution ? 
Thanks.
Regards,
Balsub123

**Comment by karawin** [comment]
Only 3.3 es_idf.
