### ISSUE TITLE
Fix the sys.ledpola Led is in Play mode

### ISSUE THREAD

**Issue by nadim24** [karawin/Ka-Radio32#182]
Hi JP.  Fix the sys.ledpola ("1") function in ## Led is in Play mode # mode.  The polarity does not change. In any case, when playing a stream, the LED always lights up. Last firmware - updated by air.

**Comment by pilnikov** [comment]
https://github.com/pilnikov/Ka_mod/commit/5a583d673b5c174d093f1fb1139f7f7bf3b99e40
