### ISSUE TITLE
Adding https station support.

### ISSUE THREAD

**Issue by hevet** [karawin/Ka-Radio32#184]
Is it possible to add https support in the next version, or is it unfortunately impossible?

**Comment by marekorok** [comment]
Hi,
waiting also for TLS support... I mean time  I have workaround with stunnel on my OpenWRT, check #132 
working for almost a year for my favorite station. 
cheers

**Comment by kgooris** [comment]
More and more radios are available only in https. We can listen less and less to these radios. Is it possible to implement support for https? Or is it not possible at all? e.g. memory limits/processing power/ SSL support ?

**Comment by karawin** [comment]
done
