### ISSUE TITLE
Support for TTGO T4

### ISSUE THREAD

**Issue by h1aji** [karawin/Ka-Radio32#186]
Looking at the description: https://www.aliexpress.com/item/32854108469.html
there is 8Mb PSRAM.
Would it be possible to make a use of it?
I remember in ka-radio there was extram piece that was identifying if there is SRAM connected.

Thanks

**Comment by karawin** [comment]
The extra ram is automatically detected on esp32 wrover.
But 

SRAM | 520 ko SRAM , SPRAM 8M
-- | --


SRAM is the same as wroom, and 4M of SPRAM is enough.
