### ISSUE TITLE
https stream support

### ISSUE THREAD

**Issue by milenmalinov** [karawin/Ka-Radio32#193]
Hello, is it possible to add ssl support. Many of the stations are already on https://

**Comment by hevet** [comment]
Four topics below https://github.com/karawin/Ka-Radio32/issues/184

**Comment by milenmalinov** [comment]
> Four topics below #184

Yes,
opened on Jul 17 by hevet and no reasonable answer.

**Comment by hevet** [comment]
Nothing meaningful has been written because there is no such possibility yet.

**Comment by karawin** [comment]
right ;-)

**Comment by pilnikov** [comment]
https://serverdoma.ru/viewtopic.php?f=70&t=1178&p=9143#p9129
in translation (in short) - possible

**Comment by karawin** [comment]
This will may be feasible on a wrover only because one htmls  connexion needs 40k of heap.

**Comment by karawin** [comment]
Done ;-)

**Comment by milenmalinov** [comment]
Thank You!

**Comment by hevet** [comment]
Will this stream work on this version? https://online.nasze.fm:9443/stream

**Comment by milenmalinov** [comment]
> Will this stream work on this version? https://online.nasze.fm:9443/stream

No! The stream is mpeg and will not work.

**Comment by karawin** [comment]
No, it say
-112 mp_exptmod error state

Don't know what it means.

Le 29/01/2021 à 11:54, Jacek a écrit :
