### ISSUE TITLE
Support for MPEG-TS streams

### ISSUE THREAD

**Issue by kholia** [karawin/Ka-Radio32#195]
The following stream plays fine in `mpv`, and VLC.

http://air.pc.cdn.bitgravity.com/air/live/pbaudio001/playlist.m3u8

```
$ mpv "http://air.pc.cdn.bitgravity.com/air/live/pbaudio001/playlist.m3u8"
 (+) Audio --aid=1 'bitrate 95060' (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:00:34 / 00:00:47 (72%) Cache: 13s/424KB
```

However, this stream doesn't load in Ka-Radio32.

Debugging this a bit:

```
$ cat playlist.m3u8 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=94325,CODECS="mp4a.40.2"
chunklist.m3u8

$ cat chunklist.m3u8 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:11341
#EXTINF:5.952,
media_11341.ts
#EXTINF:6.016,
media_11342.ts
#EXTINF:6.016,
media_11343.ts
```

It seems that MPEG-TS streams are being used.

http://provisioning.streamtheworld.com//pls/program1aac.pls <- example AAC stream which seems to load fine. This might be useful for debugging purposes.

Thank you!

**Comment by karawin** [comment]
m3u8 is not taken into account. Sorry
