### ISSUE TITLE
UTF 8

### ISSUE THREAD

**Issue by likvidator22** [karawin/Ka-Radio32#197]
Hello, You can add support for UTF-8, since the song name is not displayed in Russian.

![photo_2021-01-11_21-24-42](https://user-images.githubusercontent.com/3489848/104200942-46f17e00-543a-11eb-92e4-728aaf75dabc.jpg)

**Comment by likvidator22** [comment]
http-equiv=Content-Type content="text/html;charset=ISO-8859-1 change to http-equiv=Content-Type content="text/html;charset=UTF-8

**Comment by karawin** [comment]
the support is done in the web browser. 
Are you sure it is utf8?

![image](https://user-images.githubusercontent.com/7613191/106257133-6fd88800-621c-11eb-9ac8-154cfaa380ac.png)
