### ISSUE TITLE
Rotary Encoder doesn't change stations

### ISSUE THREAD

**Issue by clparrish** [karawin/Ka-Radio32#198]
Radio works great. I do not have a display. I have one rotary encoder implemented, which works as follows:
1. Rotating changes volume.
2. Push mutes output as long as it is held.
3. Push and rotate changes volume. This is manifested when released.
I thought it was supposed to work like this:
1. Rotating changes volume.
2. Push mutes output until it is pushed again.
3. Push and rotate selects another station. This is manifested when released.

**Comment by karawin** [comment]
Something is wrong in your configuration.
2/ is abnormal
3/ is abnormal

5/ is a start/stop
3 and 6 ???

**Comment by clparrish** [comment]
Thanks for your comments. Configuration is whatever is present in the upload, I don't know how to change it. I've reloaded several times; the behavior is the same each time the firmware is uploaded. Still mystified.

**Comment by karawin** [comment]
Without display, two encoders may be a solution, but strange.

**Comment by clparrish** [comment]
I found that there was a wiring error. The rotary control works correctly now. Thanks to karawin for the help.
