### ISSUE TITLE
Compile error bt_speaker

### ISSUE THREAD

**Issue by ArnostDvorak** [karawin/Ka-Radio32#2]
C:/msys32/home/user/Ka-Radio32/components/bt_speaker/bt_speaker.c: In function 'bt_av_hdl_stack_evt':
C:/msys32/home/user/Ka-Radio32/components/bt_speaker/bt_speaker.c:87:36: error: 'CONFIG_BT_NAME' undeclared (first use in this function)
         esp_bt_dev_set_device_name(CONFIG_BT_NAME);
                                    ^
C:/msys32/home/user/Ka-Radio32/components/bt_speaker/bt_speaker.c:87:36: note: each undeclared identifier is reported only once for each function it appears in

I used new chaintools and actual repository.

**Comment by karawin** [comment]
KaRadio32 don't use BT fo now.
Remove it in menuconfig.
A bug in the idf is detected, so the web and telnet dont work anymore.
I patched it, a correction is in progress.
See https://github.com/espressif/esp-idf/issues/1141

**Comment by karawin** [comment]
No answer. Closing

**Comment by ArnostDvorak** [comment]
Could you include the bluetooth music playback feature? Please.
Thaks

**Comment by karawin** [comment]
I tried but unsuccessful, not enough memories.
