### ISSUE TITLE
Permanently reboot

### ISSUE THREAD

**Issue by pilnikov** [karawin/Ka-Radio32#20]
A wonderful project!
Thank you very much for your work!
I have a couple of questions and suggestions.

If I specified an incorrect login and password from WiFi, the controller starts an "permanently reboot"

        if (getAutoWifi()) 
		{
			ESP_LOGE(TAG, "\nWifi Disconnected. reboot");
//			esp_restart();     // I comment this line
			ESP_LOGE(TAG, "\nWifi Disconnected. Connection tried again"); // uncomment
			esp_wifi_connect(); // uncomment
		} else
			ESP_LOGE(TAG, "\nWifi Disconnected.");
        break;

Can return everything back?
Can make control the music playback from the line input/SD card? My VS1053 has it on board.
Сan make a "truncated" version - without a built-in MP3 encoder (only for output on VS1053), but with a large buffer under Stream?
Thank you!

**Comment by karawin** [comment]
Yes sorry for the reboot. Corrected now.
No, i don't use the sd. Sure i can do it but not a priority.
The buffer is large enough even with the mp3 decoder (it take only rom flash).

**Comment by pilnikov** [comment]
Thank you!
