### ISSUE TITLE
V2.0 R1 error

### ISSUE THREAD

**Issue by Jambola77** [karawin/Ka-Radio32#202]
I have upgraded to version V2.0 R1 and now the playing stopps directly after it started:
```

##CLI.NAMESET#: 7 Antenne Vorarlberg Lounge
##CLI.URLSET#: http://webradio.antennevorarlberg.at
##CLI.PATHSET#: /lounge.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 220
##CLI.URLSET#: http://HTTP
##CLI.PATHSET#: /1.0 200 OK
##CLI.PORTSET#: 80
##CLI.STOPPED# from C_PLIST
##CLI.STOPPED# from clientConnect
##CLI.ICY0#: gethostbynam
```

Configured URL is: http://webradio.antennevorarlberg.at:80/lounge.m3u

It worked before and the station URL is correct. Any idea?

**Comment by Jambola77** [comment]
```
##CLI.NAMESET#: 7 Antenne Vorarlberg Lounge
##CLI.URLSET#: http://webradio.antennevorarlberg.at
##CLI.PATHSET#: /lounge.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 220
##CLI.URLSET#: http://HTTP
##CLI.PATHSET#: /1.0 200 OK
##CLI.PORTSET#: 80
##CLI.STOPPED# from C_PLIST
##CLI.STOPPED# from clientConnect
##CLI.ICY0#: gethostbynam
```
It worked before and the station URL is correct. Any idea?

**Comment by karawin** [comment]
For non https station the url must be webradio.antennevorarlberg.at without http://
WRONG
##CLI.URLSET#: http://webradio.antennevorarlberg.at

OK
##CLI.URLSET#: webradio.antennevorarlberg.at
##CLI.PATHSET#: /
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 56
##CLI.PLAYING#

**Comment by Jambola77** [comment]
<img width="437" alt="radio" src="https://user-images.githubusercontent.com/55683273/107695679-38082080-6cb1-11eb-93cd-0dd6b076a6cc.png">

I cannot add a station without http in the list. When I remove the http://, I have a blank URL.

**Comment by karawin** [comment]
It is normal to have the http:// in the full url.
It is parsed correctly in Url, Port Path.
You can  save it as it is.

**Comment by Jambola77** [comment]
No, it does not work. Still the same error.

**Comment by Jambola77** [comment]
I have now inserted "webradio.antennevorarlberg.at/lounge.m3u" in the radio tab in the field "Instant Play" and got the same error (gethostbyname).

**Comment by karawin** [comment]
yes that strange. I will try to find. Thanks

**Comment by Jambola77** [comment]
It worked perfectly with V1.9 R9.

**Comment by karawin** [comment]
Found. Update. It is a 2.1 R0 but not official yet ;-)
Thanks

**Comment by Jambola77** [comment]
Issue ist fixed. Thanks a lot!
