### ISSUE TITLE
 Bad display of characters

### ISSUE THREAD

**Issue by Janda008** [karawin/Ka-Radio32#204]
Hello. There is no solution to this problem. Characters are displayed incorrectly. Thanks for the info.
I'm sorry for my bad english.
![149858133_868479107280315_6654874171257842614_n](https://user-images.githubusercontent.com/79054282/107883759-1c8b5880-6ef1-11eb-80ff-f7de1542f925.jpg)

**Comment by karawin** [comment]
Name you gave to the station and station url please?

**Comment by Janda008** [comment]
Station Name "Blaník" and url "https://playerservices.streamtheworld.com:443/api/livestream-redirect/RADIO_BLANIKCZ_128.mp3"

It doesn't matter what station is playing, if these characters are to be displayed in the text "ĚŠČŘŽŤŮ / ěščřžťů" they will be displayed incorrectly on color lcd. There is no problem with monochrome LCDs. It is possible to simulate that these characters are called radio stations. Thank you for your help.

**Comment by karawin** [comment]
I made a basic mapping in the prerelease.
The problem is that the font doesn't include the full utf8 latin char . the B/w driver contains it.
So I made a rough mapping (in progress)
TEst it if you want.
command:
sys.prerelease

**Comment by Janda008** [comment]
I just tested the character editing and found that most of it is fine. 
Summary: 
Ě = E  ě = e  - OK
Š = S  š = s   - OK
Č = C  č = c  - OK
Ř = R  ř = r   - OK
Ž = Z  ž = z   - OK
Ů = U ů = u  - OK
Ť = d   ť =  e - NG

Only the "Ť / ť " is angry otherwise it's great. Thanks for a good job!

**Comment by karawin** [comment]
DOne in 2.1R1.
Far from perfect, but I will improve it  time to time.

**Comment by Janda008** [comment]
![152256437_249545706659786_2001624656636691482_n](https://user-images.githubusercontent.com/79054282/108494170-84ea8900-72a7-11eb-8a92-e7f590d1d07f.jpg)



Thank you once again!

**Comment by kauczu** [comment]
> I made a basic mapping in the prerelease. The problem is that the font doesn't include the full utf8 latin char . the B/w driver contains it. So I made a rough mapping (in progress) TEst it if you want. command: sys.prerelease

Hi there! 
Any chance to update mapping utf8 localized chars? There is a problem to display Polish characters, such as: Ś ś Ą ą Ż ż Ź ź Ć ć Ń ń Ę ę Ó ó Ł ł
Or if you out of time or something just point me to where to find this piece of code and I will try my best ;)
