### ISSUE TITLE
Using of 7pin SPI LCD

### ISSUE THREAD

**Issue by nk3535** [karawin/Ka-Radio32#208]
Hi,
I have a 7 pin SPI LCD panel (ST7789) I tried to connect but there no CS pin so i don't know what to do. Is there any possible way to use it? Thank you.

**Comment by karawin** [comment]
Depends on what is also on the spi. (vs1053?)

Read https://www.instructables.com/Adding-CS-Pin-to-13-LCD/

Just a little google search.

**Comment by nk3535** [comment]
Thank you so much for the help, i didn't even guess that i can add a pin to lcd, i have lots of things to learn :)
