### ISSUE TITLE
NEC ir setup

### ISSUE THREAD

**Issue by phanus** [karawin/Ka-Radio32#21]
First of all, thanks for awesome project and all of the hard work!
I'd like to ask, how to set up the remote control? If I enable log on debug level, I see successfully detected codes of NEC remote control keys in serial terminal. How to link them to certain actions like Volume + or - , switch to station x, etc.? I'm using v0.9 rev 4.
Thank you.

**Comment by karawin** [comment]
See addon.c function void irLoop()
You have to add your own codes for your remote.

**Comment by phanus** [comment]
Perfect! This is a piece of code I was looking for. Thank you.
BTW It would be super convenient to have the IR codes configurable over the web interface. Adding new codes to the current list increases risk of collision with some appliance you may already have. Like the TV...

**Comment by karawin** [comment]
This is a very static configuration, not really useful on the web interface, but may be on the uart interface.

**Comment by phanus** [comment]
Indeed. Similar to display configuration - you do it once at the beginning and then you can forget about it. UART would do the job.

**Comment by yura174** [comment]
help the console gives out
I (991986) addon: IR event: Channel: 0, ADDR: 206e, CMD: 7f2 = 206EF2, REPEAT: 0
I (993936) addon: IR event: Channel: 0, ADDR: 206e, CMD: bf2 = 206EF2, REPEAT: 0
I (994606) addon: IR event: Channel: 0, ADDR: 206e, CMD: ff2 = 206EF2, REPEAT: 0
I (995276) addon: IR event: Channel: 0, ADDR: 206e, CMD: 1bf2 = 206EF2, REPEAT: 0
I (995876) addon: IR event: Channel: 0, ADDR: 206e, CMD: 17f2 = 206EF2, REPEAT: 0
I (996546) addon: IR event: Channel: 0, ADDR: 206e, CMD: 13f2 = 206EF2, REPEAT: 0
I (996846) addon: IR event: Channel: 0, ADDR: 206e, CMD: 23f2 = 206EF2, REPEAT: 0
