### ISSUE TITLE
timezone setup

### ISSUE THREAD

**Issue by esaulenka** [karawin/Ka-Radio32#216]
Hello!

1. This code looks very dirty
https://github.com/karawin/Ka-Radio32/blob/571d4c9cfc7de54758d13e2592883516c9008c3d/main/interface.c#L1259

`tzoffseth` and `tzoffsetm` are only single byte variables, but `sscanf` will write 4 bytes in it. So, you will mess up nearest variables.

2. Also, please add eeprom flag that enables daylight saving time.

**Comment by karawin** [comment]
Yes, you are right, the code is wrong.
I will change it like the one I made for webserver.c
`				int offtzo= 0;  
					int offtzoh= 0;  
					sscanf(tzo,"%d:%d",&offtzoh,&offtzo);  
					g_device->tzoffseth = offtzoh;  
					g_device->tzoffsetm = offtzo; ` 

Daylight saving time is on by default. Ok, i will add it.

**Comment by esaulenka** [comment]
> Daylight saving time is on by default. 
Yes, I see. But our government already turned it off :-)

> Ok, i will add it.
Thanks for this improvement!
