### ISSUE TITLE
Wake function not working properly

### ISSUE THREAD

**Issue by jakakordez** [karawin/Ka-Radio32#22]
I am going to build a web radio based alarm clock with ESP-32, and I am very happy with your implementation. However I have found that the Wake function doesn't work as expected. It was 9:30, I paused the radio, set the wake time to 10:00, but the radio started playing in about 3 minutes. Am I doing anything wrong, or is there a bug?

When I find some time, I will also try to implement a week-day dependent waking times. In the mean time, thanks for this great project!

**Comment by karawin** [comment]
In the HH:MM format, the seconds are ignored.
What was the number of seconds in in; xxxx Sec. ?

**Comment by jakakordez** [comment]
The seconds were calculated correctly, but apparently the radio started playing before it reached zero. Will do some more tests.
