### ISSUE TITLE
2nd rotary encoder 

### ISSUE THREAD

**Issue by andrewbpowers** [karawin/Ka-Radio32#226]
Hello!

Is it possible to connect a second rotary encoder and use on for the volume and the other to select the station for example!?
And if that is possible, how? ;-)

Thanks in advance for any help and tips.

Take care...

**Comment by karawin** [comment]
https://github.com/karawin/Ka-Radio32/blob/master/HardwareConfig.md

**Comment by andrewbpowers** [comment]
Thank you very much, for this insanely detailed answer. Great work!
