### ISSUE TITLE
Feature Request: Hardware Button Control

### ISSUE THREAD

**Issue by chellmann** [karawin/Ka-Radio32#23]
Hi,

it would be great to select the stations with dedicated Buttons. For example in combination with a MPR121 breakout-board which has a I2C Interface and 12 possible inputs, even with capacitive sensing.
The rotary encoder is great to control the volume, but to switch between the first stations in the list it would be much easier with simple buttons - like on the good old car radios.

**Comment by MarcLuc** [comment]
I thank this is a good idea. Having presents station button or favourites button is a common feature on radios.

**Comment by karawin** [comment]
Yes sure, it is one of many solutions.
Rather than including this feature in the code, i think it is better to think about an external addon with a stm32 or other slow arduino cpu and a command with the serial interface.

**Comment by karawin** [comment]
Resolved since 1.4. I close it
