### ISSUE TITLE
Feature Request: HTML | Meta-Tags, Icons and Favicons

### ISSUE THREAD

**Issue by eqsone** [karawin/Ka-Radio32#234]
After all still the best Webradio around. Thanks for keeping this up!

Over time some design related things for Apple's browsers have changed and I'd love to see these added to KaRadio32's html. It would not mess up with any other of the site's functions or looks:

**Browser Status Bar:**

The meta-tag `<meta name="apple-mobile-web-app-status-bar-style" content="xxx">` became deprecated by now. If a website like KaRadio is saved to a mobile's homescreen and then opened (as webapp) from there, it'll show a big black bar on top with no battery, clock or network icons shown.

They finally changed it to `<meta name="theme-color" content="#[hex-color-value]">` well known from Androids' mobile browsers to color up surrounding browser elements. Developers can match the exact color of their website design for the browsers' top bar.

**Application Icons:**

The already embedded KaRadio32 Logo/App-Icon changed to a quite weird appearance on the homescreen over time as well. 

I found out that you don't actually have to put an image file to a directory to call within the html, instead you can add images straight to the html code as base64-value. This will make a browser itself render Favicons and Touch-Icons.

Image used to encode to base64:
![KaRadio32](https://user-images.githubusercontent.com/7477146/136528007-52ea12b6-b3e0-4a3b-af46-b079744aa7c3.png)

For an 80x80 KaRadio32 Apple-Touch-Icon it would look like this:

`<link rel="apple-touch-icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAf+ElEQVR42u17WXNl13Xet9ba+5w7YLqYgR7YzWZz6GazSdMUNVq0REqmSNGyI9vxmKFKec2Tq1KVB/2GPKSSKlelkkqq4lGWbDqWImu0JFNNSZzV7IHd7BFAA7gALi7ucM5ea+XhoJuUTSgiq8xKxTzAA3DrTt8+a33r299amz73n07hn9LF+Cd2vQf4PcDvAX4P8HuA3wP8/9AV3sFryNVJnIK7C4w8OYhYDAR3wN0BkBMRQAARwd3hDtvrPQ0gIgLDAYCJAJgbMZWW4AjE4gBgRObEBDY1pncDMEyJWTkonJHYnGDMEUYOBdycDARidmRBmlnIhZiVghIRE4FAQLUG7q5mfXV1KhMXQzOHg4kc7sw89JLBAUwOBwxkEAGLuZM7/eMDLrlGbpK6BC647qGWoyAtApkBBkRhsyKGWCNfmMiOzI7um8hnxmJrPA8hZFkWAoigirLUsiz7w3Kp3V/rFlc2+pfWexu9NCjVkgo8Ux5jCiEvSuo5qXuG1AhqKaQ45t4F9B8dsJDDlAghBHWEKDa05K4KJ4oBYzU+ND1ybGH0+IHp0ZxJJLEwIxdUd8RuhnaMkmXSaOQTIyMOd0Kv1KtrWxeWOhdXehdX+t2COMZUDBXsEiUwEWtKZGppSMHxLtzhCHMmJ2FC3QdpODCO4FqETdb92MGJk3cszNRoNFitlhGYmKIbzMmI4FWWvokSQE5MgCvYszo1FscPzIydHNjVtcFLp69c2Cx3yqhJI0xcydxIAIvoKuTtIn4ngA2iruQa2UPw4UBFwkgojx+cPrG/eaAVR5rBwTEnB1lK7GAWI0rJmImZiXdz2MxN3V0DORGZC4wjIUQ0gk3X6OD4/gs3yucvbV5c6+0MEzsFRlEmDkwkcPr7y/ePAbgwwCkwJ0cyicH2j/O9B1rHD7QWJ+u1QO4oU9nZ6DWaYyLkgJsRqEJK7jA4AAcBTHBiF08lArEnHw4HxMjqWcioPjMy0UytOk9dkVevdds9SyYAzFUZ5O8KSzMDzmAYUxbozvnx+xZrxw62Ws3IIHchIBWD0y+fPnHyZKNZgzto94LD4W43gxlEvFuPQEoMM792/TqYDh4+SERwGs/DsX0jozlNNGsvX+tfXe87RzV1MnaidyGko7CZAzZRD7fPjX3o+MKhVqhFZwISkWNnMLxw6Xp3Z8hEO5udLI/1RoOYzADaBVpdvlvYnZ0i0dZ2J2S1bllsdTqxUV9cnGfAnULAbXONidZoa2zn1JnVK+1Bd8jyjlTT3q8hAxxwuLuTg7GbMaQGuI1lfmy+8amfO3j3fJ7FUJqUykpcmrXXVi+cffXjj/yCMF25vtTtDYgIpuKJLYmruN38VfHEMFcn4gsXLrU3N47ceWR8YvzcuXNlUTCxi5UeKNammvzg4ZFP3L9wZCbLCcI17EodOMiqtXTfVTxvF7Bx4WTiRqplyQXXHGXuCufkqcb9exfyR08s7h9nDC0yIlF0C+TtjfWrS9fvPXlCMnn+hRcHg0EIoo5k7mTJkjk5CUgcbO4KU7JeUXhAlscrr1/abrf3zU1PjI2defWsuaPcYSQ3mId6Fo/ua378gfkDk0ak8NJS4eZKsUDmAtEyppAJCb9NwGyRAHVxzmLNIg2i1EtLlnyMygfvmP/w/XfOtepICvPhwJhBQiDs7OxsbW3t379/a6uztra2b9/i2Nj45UtXzpw5WyZwyI0lORJgRJAICpsbnVOnTpnp0aNH+/3+2lp7bGx8aqp1+fJlM6dYCyGUpZWFQS1j3DYz/pmPPbC/Ubqp5JFFyFLGfYYp6sg9GekeKlYefPJzb53cHNXUSDhmIRp5oUYO1Dk+cHj84bumD0zWcy+JQTGYMxHBrdfrr61vlKlcmF84derUPffcMzU1ff78a51OZ3ZurtZoJvWlG6t/9/1nX/nxmd5wWKvVsywzR1mWZ86cnZycGh0dbbfbZVnUarX19fbi4mIeooHAJExMznCB10OYHM1v9FK/hCqza+ASRoYaiWuVjvR2SMuJ4cwCFocRGRkACwdma/feNrmv1chJb+UPC6psX19vD4fDw4cOF0WxvLx88uRJANvb27Va3pqc7HT7P/jhj77wpS+trq6r6ujo6EMP/txjj37sjiOH5+fnX3nllXvuOTY1NXXlypXNzc7MzOzCwsL58+dP3H2PZCxCBEAJ5uyoeXHX/omrXf3+q+s3hn0nYxNX5pCSEnzPLN4TcHJjFmF3U01EyEioFu3YwdH9U416DEQwJ3VyhQNMYNBOt5tSOTs70+v13T3G0G63Y4wTExNmfuH1y3/0p3/2gx89VyR1RxBab7dDDAsLC6OjzVartbm52Ww2QhDAa7X6xMT4cz96/tiRoyEPFT0ZACMRYrdawL37x1bXh53+cLsgRyCzSGpG8D2r1d6k5RABwy2pO4hjMD66MHr3/pGJkYxEjCSRGAkY7g5zAGVZppREpCiKsbGxGMPS0lKtVmu1Jre2tl999cxzz7/gIDCDGSxLyyvPPf/i1atXQ5DDhw+vrKx0u90QArMAnmV5v98zUzerNp0OcmEjVgrm2DeWHTswvtBqCIm5qBMBIsmrHerbAizOTG5mZk7smfBEwPvvmZ2fyGoZE5EBzlViuTCYnBymnpKq6mAwaDabAG1tbcUYm81mb6e7dP2aajIzImJmuJtpd7uzdO26O2ZmZra3t3u9PhEDKMsUQpAQnOHm5CB3YkgkgxuBSDKmowvNuxdHJ+sZE4zgLsKgWyX+ZwecEcEkORmB2HNJd83Xju9rNgLDHG5MngkYZqWKQIRB4g4iMDMzF0Whanmeu7tqyrLQyPNADPfd6u7OQB5CnsWy1H6/32jUsyze1HNMRO4uIRAJDORgB5kJWS0jT+4JUw2+Z7F5ZKaRk0OkhJsJY89SzHtviZJ7UBJjN7Mo5fuOzeUJgDiITTmVVhRIZSaV8UAOSIwxxhBlbGys2+26+8LCQlEU7fbG+Hjr+PFj9VpO5GAndiKEIHNzs/cePxYjX79+fWpqemRkRFWJUKvlqupuFNiFNBnM4UnLHnSAooyBAEYq97eyI7P1OhFLUNaiFJK9AROhUrPubmbuTkQiUtCgS0N1yjWMix8ct0MzeYiBOLpDnZyEODAFN7HSVNVdszxCpLO9Y4TkVppOTE1ubndW2+vNkfq9x47+y3/x27kIqyFZLvL+hx78zFOPt1qjvUHx49On5+dnm82marKk5WDY3erMtKY0lZoKF3NyJ+HYpNDwEJ2I83LInAW5bYwOTXjmzoXETBhD2sMYYIB2dy5vlpVEABGcASZq5PmBucksz4jITQlgZhABu5EJoHpwZmamVqu9duGCiGRZNhwOR0YatVre7XY3NjbGJ8Y/9anHP//5z8/OzArzU099+t987nMnTpwoy2J5eXlyajKvZd3uNhx5rdbZ3l5eXjp+/HiMkQjVjWFmgNS8TKbqqk5wEWlNjB2YndBUZJScmJixB01z9XUrUvuJOCAhB8MDY7SZH9k3I8JGMLfqmX8vaKpHxsbGanm+sd6u1/L77zt57uzZrc3OodsOTU60tjudGMNka3L//v21ei2EMDk5OTs322w2NelGe+Puu+6OIT99+oyEsLCw0Ov3tzqd6dnpirqI2MxVk6q6g5mJSY3FWYjHxmr75scaOSKbg+CyJ2DcdBnf/L3d3cDkztAYMTlW2zc14hUzu/9DnLcWK4iMNJv1en2jvXHw4IFUphsrN/IsW1iYHx8fZ2bVtLy8XBSFqm5tbm13tgHkeb64ML9/38LKysr29vbY2CgzdTqdqekp7Mba7qfcJEUSIWYQhCEAxSCT47XFqQaxm7kZ/V9Y+haMm/fNzSp8Vst5aiwfyUQV1c19I4yJiJlu0qm7u/nY2PjU1NSrr55xs8OHDxdFMRj0x0ZHW60WQKp28eLF4WBoZqtrq+12m4iyLNu3bzHPsvW19YX5uZnpqfbGxlanc/j2I7vursEMFbkwc5VJRBUDUWV81jK+fa6pTjBVh/0sd/hWlFYfQ05wNGthdjzz5JYcBBJ24Ba90e4Od5fzAG82GpOtie1O5/XXL+3ftzg9NRUkujvdrEUXLlxQVRFZW1trb7SZyd1d3R0TExMHDx5Qta3NrUajMT09JSJvyriKN1B9lpkSuQNuaqqZ8P6JLDmRlwbynwL4FuafyExzIQHJSF3mRmMqFVZJnTfoym5ebnbrHURoamryfQ+977nnnivL4f79+8bGxszcDSBKKV28eLEoC3dfW11rr7crwoM7Mw4ePBBCdu78a2p674njxDD3lKwKY3eomrtXIVWWpVulNomZ65En6xVdGe9dlt5aS7s7jCQEYxqpycxISOCc4aROwsQgc3dVvYWzEhsAWWlwtMbHP/bRRwLFKu+rlSxTGgwG165diyGLMevu7LQ3NsoyCVxLD1JdevzYMRZh4qJUN4e6qt6MwUqVkojkea6JyJ1JwGgQRuu1Ri12dkpmuOEt5WUggpm/5a0PLEkoBm7kXjpLQIJ6VbyJPamqmhmAKrWIK4sKplDV4XBYrYhIJUWtLIqVGyv9fv+uY0fyWm352tXNjY2NjY2ZqcksE3e4eSrTl7/ylWee+bukyiIiwka1Wu22Qwfvv//+O+86OjLSKItiOBw2Gg2AiN3IAWbivJaP5GFjJzEpyN+St4KZv5lmb90xBBtYPw/SiDlRTUw1kUSBU0rqjrWNrW9+55mvfOXLn33isUce+QVwAwoIBql8+aWzf/AH/83Mfv/3/+2hA/uZhRww3+n2z55/HRJuP3Jbo17f7my2t7orN9YnR0eJU6LA8G53+8XTZ77zw5cWZmfuPHxQJAydbmxu/ODPn/vLv/rKJz/5+Gf/2S9PTzTJU5lKIpAEg7gDZI7haDM0Okhl5Wf6W4f0P4x3dwfBTIUliBCYYe5OznAQCIxhUVxbXnnl9JmPvu9+EBMHEJLqmfMXvvClL73w8ku/89u/NT4+BoJaAjMFLjVdvnwFxPv37RsdHTl79vxWp7O+3g53HyVTCUxuzOju9JL5Pcfu+Y1fedKcCwKKwSsvvvL0X3/1r//3V6emW7/xq0+KMViA9IbucRAQA1c9qN0H345r6bcykxhk5O5wA5iYblZGqhbWDRKIgaUrN/7228+88MKLD/38yScef6w1Pi5EN1+GoiivXr3GTNudjmkqymIwGN5YXSMWEJmTgIgEQB6zxYWFk/edcLABDLvj8O0r65tP//VXvvf973/qkx9rZIFJdusj+U3DV5gZtxZgDy1Ne/JWhYreUCNvKmDgXQUONTc4CJ3t7vdP/eh733t2anLyn//ar+5fnI3MQiQixHD3Xn9w+erVEMJUa2J2emqk0ehsbS0trzgAYSc4qOod7maXmhACgGRTk60jd9xeH2leXbre2e5W9YUgMGCXg4hYALnpd/8MLF2V1jc3fd6oybuY7U3ZXrm4ADGLFMlfeOmVr339293t3q9/9tPvf/ihyOQKEnIikKtpd6e3tLw80mx+8rFHF+fnr1y5fu78hZXVG0k1skgkpDd0vbsBRgDtfgHUGvUsz8qyVKv0IxhUKeNdOQBRJXX6KR0Y/nuq2G9eu8XYTNXcdtXdLtNXPSFzBzmQ13IHrdzY+Mu/+vKFC6/9woc/9JmnniS4pUQBBIK7V/5ee31YDGdmZiwVw0G/XqvFGDe3ttY3NlNyN7gZABZmEQK5Ocx3e8jqmirOF2EhorJUM8B5V2wZXFEUyfDTmsbhTRrrJ2QyETmgqpVrk8XAzG5VY97V1NwlCIVYJnPgD//oj5859exHP/Th3/qNXxkbqVlSEFsyIlc3h3d3eteWV1iEzP/8C1/Ks3jm3EV33+n1lm7cWJybTlVwujNzkMAS1Gm3fxQkJb1+bWlleeXOOw43GnW3JDGvPHcDmTuZJbVeb+DV/d4ji8NbZ28F2D2lVBRFShpDoN1q7lVpFaHKzSmK4otffPpvvv6Nu+85/slPPjo/N6mlqSPfNURMnAjc3d65fOVKlPiJTzz6xKOPNBv1Z597cfBnX1xbX790+fKJOw5LXk9aplSklNQVRDGL6kBA6uvX/uZrX/vqV5t57ZEPfWRibJTIwEwlQHSzPeJlmbq9vjlDsNd0xZ4sTQQ316QpJVVFtWoEx+7WTERijCmll1758cXXX2+OjD/22MfvPX5UUKqHGEOpJAQ1JXNB2NneWVpezvLszjvvnJqequfZwYMHZ2dmLl+5sry0FISJEbMMROZ2/frSH//pn77y/A/KZKjlZW/n+uWrxPGpJ5588vFfIlez0syCxcr9h3ml/IaD0jn/KU3U8A/9vSql1dWQjMLWkNe7RWO0RswG4aqDb+Tm7lqWJQibmxvjkjWbI7XaqGkiMksFEFSFWABX983u1pWla066trr8/AsWJaxtbPYHO91B9/LSEjgUvW6MOSQzCiIy2mw2Go3Tp0+/8vrlu4/c/sEPfOD++07ee+LehYVZIyeOnBhcDKuRD+Jh0qVOr4eQAU7k9NbSck9PS11BIAlbQ7u+2QPBHE5cbUPo5t5HmA4e2P+JRx81TadOnXrttdeJY+WaSwATCEIcDNbpdjba7ZlWa25yUpygPt4cmZ1qCWFpaXlYJqiC4ByIw/jY+M+dPPnrv/bZpz79RAzi7g+//+HHHv3FI7cfrDQQcxQWYgO5g8DUL/X19Z4xk8DU3PzthbS5B84CS3cwuLqZPWzsblS577xb5ogoz7PJVuv9j//SxvbOs8+emm6NTU+1Zmdau0asmSY4Y6fXb69veGlHbz/ywMmTrE6AMS3duPHMqR9stTe2Op3Z8RFmqXYatVo+OzvzwP3379+/73s/fPHHr7x88dKle+89VmvUhWBWSRkQUfTATg7bKfTSjV4kUwlpYEzO/LaaacygwKCdQXltc7jTN1atOjbuVblSVSUi1fLQbQee+NTj46Mj3/nuM9/67qnt/sAc1R4Cbqa+urq+tLxSb9QPHT6U1Wv1kWZ9pJk36pPT0zOzs4Ph8NrSslOlCR1mrmqmRDQ3N/u7v/mbk63WN779rR89/8JgOGSQELt5MnMwE7FrKtPaTnltowhwI6G9G6Z7Ag4UDZTMSsVmzy+1h1IZ5MLEbGaakqlamWpZFgQf+sDDn3jsY5ubW3/2xb98+fQ5MIHZCRIoBO50u6sbm1mjPjk3u9nttrudjZ3tje42ooxOTvSL4txrF5OaqZol09JNhTlmwsSPfOTDH/rAB86eP/edZ763tLJiCktGDLVkLgCx23avuLw+2CnNQeYcorDQ2wvpgJAciTyCewN94Ur7xMI+BiAwQwix0Ww26nVih3sqNW+GJx5/vL3W+eM/f/q//Nf/fuTwv5+fnih63RiiSVxrb15fWul1u5def/1/7ewUwwEBLGGz2127sdrZ2nrtwqWytKweiTiIxCDkrskAiOH3fvt3Xjr98je/8c07Dh4+8q/+tRNcLc8zqvKUw1pncGG5FwLUAhIR70nTe3cPtcoBFkZRlmeXtq5vzc6NVj00MEE1lWUpLKpJQAyfGB997OO/2N7Y+tZ3v/0f/uN//vy/+/0YM2KWyJtbmzdWVhen5379l39lujVhKVVG79Z2t5E3Xn359NVr1zkGU4VbWQ7LcuiuWiYwMfH8/OynH3/yf/7RH37nu9+799ixD37g/WoJyQICCW0P7PJ6/9r6NpEpRTYry2G1N38bIe0ONidXcy3UN7fL5y5tdnqlqTI5AFOrTCyYETwKRaE7Dh342C98+PChw9/81t9+4S+e7pWlEw2GaXOz0+/1piZbB/YvToyPTbZarcmJVmt8fn5u38JiDPHC65fUnJliDFmMgYWZQwxExAICHvnwRx48+cBrFy588emn17Y2OIiAYK6lX13fubCy3RuUlipNmeD2todaiIkr4cHOFILSCxfXj81xsz7CzA4XkbGxsfm5udbExK1Fqtfz+04ce2r7if/xJ3/yN9/41vseOHlw32Jnu7u+sVlo6g2HX//2t7UsGCSBHUjqr54/J1ns7uwsL68c2DfXbDQe+egjR2+//YH7jlXMQ0Ix8r7Fuac+/eTC4mJ9tDHUxMyUzDQNh3ZpafPqeocZRckhKtjC3gNrewIuKJFrABykToXJ9Y3ypcubo2ONVnRTq9caD9x371hd7jt2NKtl1bbU4GOt0Q9+4OdDxMZ6O4q4U3ujs7mxNdJs3nbb/jzPSiAEEpakxuJTUxMHDi6+dunKxauXp6db9Vrjg+97MN1/otmomxoTwZIEIaf7Txw/fOhQL5W1eh1wKIbk51e3zizvtPswBLIyqCuDJGLXN/yZAZekDMs4CEtffcgwDz+6sDU3N34soibSbNbvO37XgyeOwo2ZTdXAygTY7NT4Zx5/lEDFsOQga2vrmxubM63JD7zv5x/5yIe11CwKgDKpOS5duXTt+tVXzp29eO3q/fedGCFMj48wizlUNeYhpQJqQiGP2fRkSHATNoOAbuyUz13ZuLxZFMhgKZJFF01IDNqj9bA3S1tgOIEcRmwi6ubt3vCHZ1fG49yh+YmYMbkWpYsE0kSpLCWShIyZzN3UgJhlCLSyury6vpbFEGNcW1uDoRpzVnOH9/uDZqMJw8ULr6umEEO1fSEigTjBYuY7O8REMTpMoJGzpCjJfnxx48pyfziEkKNqkrO7umq5l1G7J2AxEWKwG5VEziicQqfQl69sTDXzkXp9fipXKxUS4VCHZCxMAKnD3MzKosgbDQe1Nzc2O5uNPD9z+tXVlRsM2vWxiRzoD/o3lpbZ+cL5i9vb/dkphykACQHubhTFypAZmMlR7QZTkVJ4bbX/4sXu0oYmChLNPDm7BXJTcq+E2NvytAwixuQkMPekRC5ZvWf+zMXNvJ5/MJ+ayCzCRS1RRsKBVZOlRCEEiZmECKEy+fLq6mA4/ODDD//e7/xuJUit8plv+qRnzp3/+t9+f/nacuUUigRicnNzN02RXGrBDZ6UzIhRul7bLp5+7urVTS04BmGQqpqBS4MTBeGbdszPDjhYohLOMCaPMCVojJFFulp8/2LbIB+9e2aylpzYAEpDDsIQMJzcS2WRskyr7Y2N9noQnpqaGBttqvote6z6g4imWq35+fmrly6trq0fOLAQslAOhylpltUAwIKQGtzJmVFALm35Xzx76Vp7UHJGkRzJ1EwDmNXInYTEYG856PFTxhXdPCUr1MxdGIEgcEMqzXBju/zBa+vfPb3W7kd1CkIiESYwhjM5gbhUZeb19bXtTmdyfHxxfoHBgZmZRTgEEeEgEojree3wwYMEX11d6ff7u+1QCermTsngLgRmQl/p7Er55R+tnFsuCy0chXuR0lBVAWEE8qrN5XtJrb3rsLN4IrdqxhdMYFItLVG1f1jvFD+4sDEs7aEjE7OtEISr8XSnKn2Y1M29t9PTspyZmlqcm3etvLc3dWcdcORZdvjwbd/5lu7sdMuyBJFI2C3CRDBKCnPe6RfnVrqnLnTPXuulIhErk/puf6my5owpgdyT+x4t8T0n8UhDZARxJqgDQhRgmthZiAMBwE6pq1uD3kAzkbF6yCpmrIQY3NyrfpKq3XXnHQ/cd9/YyEgVVXaTh5l2j71k9ZzgDz/80MLCfJ5lAJlV09QsBjVd2ey/eHnz2fObry11y6TsJZEHz6Rq8bAAIJSBU2DWxL6HU0t7nR/mFEIwFk3uhQIiLGRlEhdhdlgydyKhSGVx377Rh+6aXpwZa42EPCKlymy1LAZN1tnuxhhGRxpIDpAzzG+2qKp5XYayr95Yb7UmYhAiMnVLRiAW2Rx4e2vz5ctrL1zuLncMzoxkMGYWi85ubAq4GayM7MJxOGRnfysp/VMMgJCKatQPxASYw5zBTl6wmsNADInMCPz8pZVrW92jt++777axAxMUmHMRYUZp7N4aHSVmr6QPETmE+A1LuLLDWWamp+HK7pVD4+Bhst5g+Oxy8cq5K9eW2oUGjg0jLpQJIOECJXz3XAsBoJgcSYHgb3v08KfNWCsEFTuomcXAlOfr3Z2d0+cvX2se3jd54tDU3QuR3ZCUEN3ZzEDgLOw2lm+17HYNflBpRKTKboULjMNm8h9f671yae31y0s7/aFT4BjdPNkQZMSUkjL2HF7Zk5vewZF4tt1jVKWmUssYYojsALmBnJgbMd83NXHfoem7F2ozDc/YCWIkZk5v6ro7bhqscArkXjpspwyX1/X05c75a+31zo65WWIQnJHcilS6W4xRgqgmN8K7cASgMmyZKZMgRuauasTCUoOqD9PAyotr7SsbnW++nM2MZIutbKGVzTRlosZZluV5nmWBiFLSoiiGw6I/LNZ2dG3brm4UK920NSgHqUxlSpZSYbV8VJOmVFZ5W42VkDKZ+Ns90/LOADuzAm7K7BKY1CtnBlqZa+5K1qcCqU3pRm9weUtGrkszUM4gIhauhlHcqh9TQ5nQLW1rmLpDTQomClULJXi/LMwU0Kr3T0RqUANRBirwNjG/o3NLDDV3M4GLV0MHDAicnAJxcGKAIpRcUWo3ld0eVecTdkG+aaSEiJiYiN3N3dgQiMHVuGQMHBJMhMi56ia4kxm5U+AAlO8G4JtTHdXINswSM5OIGRiozFmH46YJ6QCxg+G7X5ur4yO7kx/EDkC1WgQBCcMp3TygSkQugWFku65pRXOm0HdwrOUdsTRV2zsKzAQkdQUIbmQMrwZe3eBMCjYCO8TAIJAQ3OkNjVupA3JwsgQyJhDYjczc1chJWI3Z3iSomMBmpiy7Y8XvAmCouSVVMhF2IvfK2lIzdkQIeQDBxCxid5pTDU6KN2a78EaJclAm4jfH6BxEEZwRDObCTiQgB1vVozYrnUxiQOHvxlE8SyUB1cSYuu0eDjPw7lakrML51knoW925N/roP8H4u29qN/9nANBbTyOHJX1zZ1MoCICBvXck/j3A7wF+D/D/79f/AUnVtSTRKJpgAAAAAElFTkSuQmCC"/>`

And for a 16x16 KaRadio32 Favicon it would be like this:

`<link rel="shortcut icon" href="data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAADKl2X/ypdl/8qXZf/Kl2X/ypdl/8uYZ//LmGf/ypdl/8qXZf/LmGf/y5hn/8qXZf/Kl2X/ypdl/8qXZf/Kl2X/ypdl/8qXZf/Kl2X/zJhl/8uYZv/Jkl7/yJJc/8mXY//Kl2T/yJFe/8iSXP/LmGb/zJhl/8qXZf/Kl2X/ypdl/8qXZf/Kl2X/yphm/8qWZP/GkmD/17KO/+7ayv/16eP/9erk//De0P/ct5b/x5Ni/8qWY//KmGf/ypdl/8qXZf/Kl2X/yphm/8uXY//LmGT/6tLC///////T0tX/6+js//Pv8//KyMv//////+zazP/OnGv/ypVi/8qXZv/Kl2X/ypdl/8uYZv/Kk1//4825//j6/////v//ubOw/7q1sv++ubf/s62q///////7/f//6dfJ/8uUYv/Kl2X/ypdl/8qYZ//Ikl7/3LKM/+zo6/+6s7L/wLi3/8fBwv+zrav/ubOy/66npf/SzM3/vLW0//f2/P/duJb/yJJc/8qYZ//LmWj/xZBa/+nSv//39fr/fHFq/9XP0f/59/n/pqCe/7KsrP/Dvr3/f3dz/6+pqP//////6dbH/8iSXf/LmGf/y5hn/8eTXv/y4db/8e3y/5eMiP+9trf//fr9/52Wk/+jnJn/zMfG/764t/+wqqf/5ePn//ns5f/KlmT/ypdl/8qYZv/Jk1//8N7R//Px9v/b1tj/087P//Ls7/+jnJr/mZKO/+vn6f+po6L/vbe3//f3+//06eD/ypZk/8qXZf/KmGf/yJFc/+TLtP////////3//+/q7f/08PL/urSy/62npP/38/b/5ODi///+////////69fJ/8iSXf/KmGf/yphm/8mUYP/UqoP//Pn+//z4+//d2Nr/5uPk/3tybf9sY13/5uLj/9zY2v/69vj//////9u1lP/Ikl3/yphn/8qXZf/LmWf/yZNd/+PKtv//////39rc/+Hc3v+poZ7/oJiU/+Ld3f/d19j//////+zZyv/KlGD/y5dm/8qXZf/Kl2X/ypdl/8qXZP/JlWP/6dO+//Px9v/u7fL////////////x7/X/8fH2/+/bzv/LmWn/yZZj/8uYZ//Kl2X/ypdl/8qXZf/Kl2b/ypZk/8mTXv/Xso3/7NjI//Ll3v/x5d7/7drN/9u4l//JlF//y5Vk/8qYZv/Kl2X/ypdl/8qXZf/Kl2X/ypdl/8qXZf/LmGb/x5Jd/8iRXf/JlmP/yZZj/8iSXf/HkVz/ypdl/8uXZv/Kl2X/ypdl/8qXZf/Kl2X/ypdl/8qXZf/Kl2X/ypdl/8uYZ//KmGf/ypdl/8qXZf/KmGf/y5hn/8qXZf/Kl2X/ypdl/8qXZf/Kl2X/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==" />
`

**Comment by karawin** [comment]
Thanks.
I will implement the theme-color and the shortcut icon soon.

**Comment by eqsone** [comment]
That’s great news, thanks a lot for all your efforts!
