### ISSUE TITLE
ILI9225 display

### ISSUE THREAD

**Issue by valera39** [karawin/Ka-Radio32#258]
Hello! Please add support for ILI9225 display

**Comment by h1aji** [comment]
@valera39 there is already opened ticket https://github.com/karawin/Ka-Radio32/issues/251

**Comment by valera39** [comment]
So I am not alone, we will wait that the author of the project will answer

**Comment by karawin** [comment]
KaRadio32 supports about 34 lcd types.
It is not a so common feature.
Please understand that the software cannot support all  existing or future lcd types.
Sorry. But it is an open source. Try to add it ;-)

**Comment by h1aji** [comment]
> So I am not alone, we will wait that the author of the project will answer

You are not alone, but you dont need to duplicate tickets
