### ISSUE TITLE
Connection of a 1.3 inch display

### ISSUE THREAD

**Issue by aternos24h** [karawin/Ka-Radio32#269]
Hi!
Do you know how to connect the following: https: //shopee.pl/1PCS-4PIN-1.3-OLED-module-white-blue-color-128X64-1.3-inch-OLED-LCD-LED-Display-Module-1.3-IIC -I2C-Communicate-i.590042449.13256450775? Sp_atk = db5a96ee-a74d-430c-8170-f4de43143e21 & xptdk = db5a96ee-a74d-430c-8170-f4de43143e21
Display for esp32?

**Comment by aternos24h** [comment]
![esp32](https://user-images.githubusercontent.com/87474945/177016493-b352416a-68d9-4bfe-8c82-68051d6e1211.png)
it is exactly this esp32 model

**Comment by aternos24h** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/87474945/177016560-c2392409-86e8-449c-9b98-1350f8f50564.png)
I followed this scheme, but it turned out to be a different display ...

**Comment by karawin** [comment]
Read a bit more the document please.
