### ISSUE TITLE
Max98357a (purple pcb one)dac is not working

### ISSUE THREAD

**Issue by JayB7076** [karawin/Ka-Radio32#270]
I don't know why my max98357a dac (purple colour pcb one) is not working.Did I need to change something like library or pins?
And I used Esp32 Wroom board and there is no pin 15-16, so can I change it from standard adb?

thanks to the developer of Karadio this is a great project.

**Comment by karawin** [comment]
Don't know. Is SD high?

**Comment by JayB7076** [comment]
No I only connected VCC-Ground and three pins for i2s communication.

**Comment by JayB7076** [comment]
I uploaded Karadio32-Karadio32-partition-bootloader-standard_adb
And I used Esp32 30pin Wroom board
In first power on display not worked than I realised that I not uploaded standard_adb
And after uploading it display and rotary encoder working normally but dac is still not working.
