### ISSUE TITLE
fatal error: crypto\sha1_i.h: No such file or directory

### ISSUE THREAD

**Issue by rihani** [karawin/Ka-Radio32#3]
Any idea to resolve the following issue when running this command.

make -j5 clean; make -j5; make flash

issue:
...
..
.
CC build/libsodium/libsodium/src/libsodium/sodium/version.o
CC build/libsodium/port/crypto_hash_mbedtls/crypto_hash_sha256_mbedtls.o
CC build/libsodium/port/crypto_hash_mbedtls/crypto_hash_sha512_mbedtls.o
AR build/libsodium/liblibsodium.a
CC build/main/ClickEncoder.o
In file included from /Users/ossama/esp/Ka-Radio32/main/include/webserver.h:13:0,
                 from /Users/ossama/esp/Ka-Radio32/main/./ClickEncoder.c:20:
/Users/ossama/esp/Ka-Radio32/main/include/websocket.h:18:27: fatal error: crypto\sha1_i.h: No such file or directory
compilation terminated.
make[1]: *** [ClickEncoder.o] Error 1
make: *** [component-main-build] Error 2

**Comment by karawin** [comment]
Corrected now. It was a \ in place of /
