### ISSUE TITLE
Ka-Radio32 ST7735s connection clarification

### ISSUE THREAD

**Issue by Alnoor55** [karawin/Ka-Radio32#35]
Pin 3 on the schematic for ST7735s connections is MOSI but the label on the display for ST7735s is SDA.
please correct schematic.
[20180606171940.pdf](https://github.com/karawin/Ka-Radio32/files/2078167/20180606171940.pdf)

**Comment by karawin** [comment]
Look at the comment of
// HSPI pins
//-----------
#define PIN_NUM_MISO GPIO_NUM_19 	// Master Input, Slave Output
#define PIN_NUM_MOSI GPIO_NUM_23	// Master Output, Slave Input   Named Data or SDA or D1 for oled
#define PIN_NUM_CLK  GPIO_NUM_18 	// Master clock  Named SCL or SCK or D0 for oled

The schematic must be as generic as possible.
