### ISSUE TITLE
Board support (TTGO ESP32 Tm Music)

### ISSUE THREAD

**Issue by joaofl** [karawin/Ka-Radio32#36]
I've been trying to port your code to this board. The job tasks are simple. It includes changing a couple of IOs, configuring the proper LCD, push buttons, and It should be good. I'm specially interested on this [board](https://www.aliexpress.com/item/TTGO-ESP32-Tm-Music-albums-2-4-inch-TFT-PCM5102A-SD-WiFi-Module-Bluetooth-development-board/32848902211.html?spm=a2g0s.9042311.0.0.6e444c4d6M7uWZ). Find the schematic [here](http://www.ttgobbs.com/attachment.php?aid=ODF8NDgyMDYyYzh8MTUyODkwNzQyNXw5YmI5L05icVViVmhKd2xvdDdUZm5XcERGelY2ZWV1ejRGNUdYZ0Z0Q0ZGbzRzbw%3D%3D) It uses the PCM5102 I2S DAC.

Its the most complete ready-to-run solution I found. relatively low cost.

But now, as I'm trying to do that, I went through one issue, and one question:

- How do you think it is a good idea to have a complete board support? Instead of changing individual configs, but having a whole config-set for an specific board? I tough of having some pre-set config structures, that could be changed on the terminal (something like having **renderer_config** and **board_config** pre-sets for a given board. How does this sound? I could contribute on that. I'm quiet interested on getting this board to work smoothy.

- My other issue, which is more technical one: I've been trying for the last couple of weeks to get the audio playing fine. Issue is that I'm always getting musics playing as if they were in fast-forward, with noise as well. I tried changing sampling rate, master clock, clock sources, etc.. Nothing solves the issue.

I found a fork of the the KaRadio from which, If I flash the binaries already compiled, it works, otherwise, it does not. Really dont know where to look more. 

It seems that there is a related issue [here](https://www.esp32.com/viewtopic.php?f=13&t=1834&p=11909&hilit=pcm5102#p11909), but not sure it solves the issue Im having.

**Comment by joaofl** [comment]
> My other issue, which is more technical one: I've been trying for the last couple of weeks to get the audio playing fine. Issue is that I'm always getting musics playing as if they were in fast-forward, with noise as well. I tried changing sampling rate, master clock, clock sources, etc.. Nothing solves the issue.

I found out why and how to solve it. Its basically the I2S library that got major updates lately. By using the latest IDF with the previous I2S library version, I managed to compile and get radio working. Now I have to figure out a way to get it working without downgrading. Need to investigate more.

**Comment by karawin** [comment]
Ok, I  will try to investigazte too.
Thanks

**Comment by karawin** [comment]
Changed API to the new ones, but something else is wrong. Investigation again and again....

**Comment by joaofl** [comment]
I saw some commits of yours. DO they solve the issue? Did you get ir working with IDF v3?

**Comment by karawin** [comment]
No. I plan to integrate the old i2s driver in KaraDio32.
It seems a problem of bitrate but unable to find a solution.

**Comment by joaofl** [comment]
Ok. It may be a temporary solution right? By replacing the deprecated I2S functions with the new implementations doesn't do the job?
I'll see what I can find as well.

**Comment by karawin** [comment]
No, in fact in the code the old api is simply a call of the new api.
I will integrate the old driver and try to find where is the problem with the new code. May be i will ask some help on the espressif forum.

**Comment by pilnikov** [comment]
lock my repo https://github.com/pilnikov/KaRadio32_fork. I updated and patched problem with i2s (Replacing with old). My ttgo play music fine.

**Comment by pilnikov** [comment]
updated to 1.3r1. Does not work at full strength (screen problems) in version 2 bugs promised (JP) to eliminate

**Comment by karawin** [comment]
I think we can close it now ;-)
https://youtu.be/Jk8d02b-uso

**Comment by karawin** [comment]
http://karadio.karawin.fr/ttgo.zip
The spi init is in the vs1053. Yes some details must be finished.

**Comment by pilnikov** [comment]
JP tnx, all work fine! Even with 255 for VS & display #199. Tnx!
Small bug - when switching stations, Cyrillic names are displayed in the wrong encoding for the first time.
1. Playing station #2 (Name on latin)
![p_20181126_112643](https://user-images.githubusercontent.com/25922873/48996510-37d1e800-f16e-11e8-808b-c433b7dbbd7a.jpg)
2. Tru change station on #0 (Name on cyrillic) - picture is not correct.
![p_20181126_112324](https://user-images.githubusercontent.com/25922873/48996604-7d8eb080-f16e-11e8-83f0-2d84428aa69a.jpg)
3. After changing the station, when the encoding also changed and changed the font
![p_20181126_112333](https://user-images.githubusercontent.com/25922873/48996685-cfcfd180-f16e-11e8-9f94-ab457ab7936d.jpg)
4. Try to switch the station again - everything shows correctly (font also changed)
![p_20181126_112338](https://user-images.githubusercontent.com/25922873/48996724-fb52bc00-f16e-11e8-97b5-7c278ac3940a.jpg)
![p_20181126_112350](https://user-images.githubusercontent.com/25922873/48996751-0e658c00-f16f-11e8-8a6a-97fb29171198.jpg)
If go back to step 1 - the bug will repeat.

**Comment by karawin** [comment]
Must be ok now in 1.5 R5

**Comment by pilnikov** [comment]
Without changes. Incorrect display of the title on the splash screen only.

**Comment by karawin** [comment]
Yes sorry, now it's ok in 1.6 R0

**Comment by karawin** [comment]
Great. I close it
