### ISSUE TITLE
Feature request: add url command to play next station. Now we have to set station (command play=123)

### ISSUE THREAD

**Issue by X-NoNAME** [karawin/Ka-Radio32#39]
Feature request: add url command to play next station. Now we have to set exact station (command play=123)

It would be great if we had opportunity to play next station by command like this http://{IP}/?next

**Comment by karawin** [comment]
Why not. I will add it soon.

**Comment by karawin** [comment]
Done

**Comment by pilnikov** [comment]
Hello J.P. I want to use the radio as an alarm clock. And to ensure reliability (I don't want to oversleep!) I need strong feedback, which shows that the stream is really played. Is there something suitable?
Thanks.

**Comment by karawin** [comment]
Closing because done.
pilnikov please open another issue
