### ISSUE TITLE
Wiring 

### ISSUE THREAD

**Issue by tomasf71** [karawin/Ka-Radio32#4]
Hi Jean-Pierre, I tried to transfer your text description of wiring to scheme. Could you check it. When I finish it, I can share with you to public in your repository. 
<img width="522" alt="snimek obrazovky 2017-11-05 v 19 52 55" src="https://user-images.githubusercontent.com/24761306/32418054-f9e77072-c262-11e7-872a-9ced33fadcab.png">

**Comment by karawin** [comment]
I think that the led must be connected to gnd and not 3.3v. I like a very small flash on it.
Great job.
Not finished to check.

**Comment by karawin** [comment]
A connector for lcd I2C?

**Comment by tomasf71** [comment]
<img width="742" alt="snimek obrazovky 2017-11-05 v 22 02 36" src="https://user-images.githubusercontent.com/24761306/32419106-14247590-c275-11e7-92e3-a7675456c844.png">

**Comment by karawin** [comment]
Seems ok now.

**Comment by tomasf71** [comment]
Thank you for your checking. Here you are. If anything to change, just let me know.
[scheme.pdf](https://github.com/karawin/Ka-Radio32/files/1444448/scheme.pdf)
