### ISSUE TITLE
LCD ST7920 does not work correctly on 1.3

### ISSUE THREAD

**Issue by HIMjack666** [karawin/Ka-Radio32#46]
worked well on the version 0.9, but on 1.3 like this:
<a href='https://postimages.org/' target='_blank'><img src='https://s22.postimg.cc/5arsx41kh/IMAG0121.jpg' border='0' alt='IMAG0121'/></a>
PS: sys.lcd("73")

**Comment by emax73** [comment]
SPI Clock for this controller is 1.25 MHz,
Now frequency 10 MHz,
maybe try

**Comment by HIMjack666** [comment]
emax73, thank you a lot. Working good on 1 MHz.

**Comment by ArnLil** [comment]
Hi, i have the same problem with ST7920, i am on the latest version 2.1.  For me this is a new install set-up. 
I also use a VS1053 for encoding the data.  When i choose DAC for example, the display is working fine. So there is a problem witch the combination of ST7920 and the VS1053.

**Comment by Shtirlitsus** [comment]
same problem with combination of ST7920 and the VS1053. How to use different SPI interfaces on LCD and VS1053 decoder?

**Comment by ArnLil** [comment]
HI, my problem was solved bij adding a diode in the data line.  (timing problem)

 

Van: Shtirlitsus ***@***.***> 
Verzonden: maandag 19 december 2022 08:06
Aan: karawin/Ka-Radio32 ***@***.***>
CC: ArnLil ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [karawin/Ka-Radio32] LCD ST7920 does not work correctly on 1.3 (#46)

 

same problem with combination of ST7920 and the VS1053. How to use different SPI interfaces on LCD and VS1053 decoder?

**Comment by Shtirlitsus** [comment]
MOSI line?

**Comment by ArnLil** [comment]
Not sure, but i think that is the data line.

 

Van: Shtirlitsus ***@***.***> 
Verzonden: maandag 19 december 2022 10:42
Aan: karawin/Ka-Radio32 ***@***.***>
CC: ArnLil ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [karawin/Ka-Radio32] LCD ST7920 does not work correctly on 1.3 (#46)

 

MOSI line?
