### ISSUE TITLE
How to connect to an class D amplifier?

### ISSUE THREAD

**Issue by Primus007** [karawin/Ka-Radio32#47]
Please can anyone instruct me how can i connect the esp32 karadio to an class d amplifier?

thank you.

**Comment by Primus007** [comment]
Thank you. Can you please tell me where and how to wire this?

**Comment by karawin** [comment]
![image](https://user-images.githubusercontent.com/7613191/45435030-faea6f00-b6af-11e8-929b-bc38836dbc3f.png)
For each one, left and right

**Comment by Primus007** [comment]
thank you again :)
i think between karadio out and clss d amplifier in?
