### ISSUE TITLE
I2C monochrome LCD support

### ISSUE THREAD

**Issue by h1aji** [karawin/Ka-Radio32#49]
Hi. I wonder if you plan to support monochrome LCDs: 16x2, 16x4 and 20x4.
I have recently purchased one like this https://fr.aliexpress.com/item/Blue-Display-IIC-I2C-TWI-SPI-Serial-Interface-2004-20X4-Character-LCD-Module/32800324987.html
and wonder how can i make it working.

Thanks

**Comment by karawin** [comment]
No support planned.
But you can take some examples on the addon for KaRadio. [https://github.com/karawin/karadio-addons](https://github.com/karawin/karadio-addons)
It is easy to adapt one to your lcd.
