### ISSUE TITLE
After Udate to R4 no sound anymore

### ISSUE THREAD

**Issue by franki29** [karawin/Ka-Radio32#53]
Hi,
i updated V1.3 R3 to R4 and now i have no sound anymore.
I am using a VS1053 audio interface.

Br. Frank

**Comment by karawin** [comment]
I wonder how it is possible.
Check volume and choice of output in setting please.

**Comment by emax73** [comment]
When VS1053 unavailable, for example, ESP32 turn off from socket during firmware update, Output toggle to I2S, need point to VS1053 again

**Comment by franki29** [comment]
Hi all,
thanks for answer. Switching off and waiting some time solve the problem.
Thanks for helping
Frank
