### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by pilnikov** [karawin/Ka-Radio32#65]
When compiling, I get a link error. The error appeared after the IDF update. I think this is an IDF error, not a project.
![image](https://user-images.githubusercontent.com/25922873/48820762-29538d00-ed78-11e8-9f89-90cd69bc33f7.png)
Source is original. No changes were made.

**Comment by pilnikov** [comment]
I spent 2 days trying to build version 1.5 with the updated ESP-IDF (https://github.com/espressif/esp-idf/releases/tag/v3.2-beta1) - I constantly received errors linker and esptool.py. Worked ONLY with the version of the ESP-IDF 3.1.1! Be careful!
JP please replace in nvs_partition_generator.sh -  ../esp-idf/ to "$ {IDF_PATH} /

**Comment by karawin** [comment]
#!/bin/bash
echo python ${IDF_PATH}/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py $1.csv build/$1.bin 8192
python ${IDF_PATH}/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py $1.csv build/$1.bin 8192
echo done

**Comment by pilnikov** [comment]
ok! fine!

**Comment by karawin** [comment]
#!/bin/bash
filename=$(basename "$1")
fname="${filename%.*}"
echo python ${IDF_PATH}/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py ${fname}.csv build/${fname}.bin 8192
python ${IDF_PATH}/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py ${fname}.csv build/${fname}.bin 8192
echo done

**Comment by pilnikov** [comment]
very flexible - very good!
