### ISSUE TITLE
How to install the Ka-Radio32 to ESP32 board? [SOLVED]

### ISSUE THREAD

**Issue by wieb18** [karawin/Ka-Radio32#68]
Hello,

I am very very new to Arduino, just few days ago bought new ESP32 and VS1053 boards.

![esp32](https://user-images.githubusercontent.com/45317320/48972024-98bdcb00-f05d-11e8-9601-ee2d18979ecf.jpg)

![vs1053](https://user-images.githubusercontent.com/45317320/48971997-e554d680-f05c-11e8-9b9d-29f3db400a31.jpg)

Trying flash Ka-Radio32 to my ESP32 with ESP Flash Download Tool v2.3:

![2018-11-25_02-57-49](https://user-images.githubusercontent.com/45317320/48972042-f9e59e80-f05d-11e8-80a4-555785553de6.jpg)

And... the result is **FAIL**

![2018-11-25_02-52-18](https://user-images.githubusercontent.com/45317320/48972046-0cf86e80-f05e-11e8-82b6-d14e7135eeaf.jpg)

The error message: **CHIP SYNC ERROR**

But when I press BOOT button on ESP32 then click START button on ESP Flash Download Tool v2.3:

![2018-11-25_02-55-01](https://user-images.githubusercontent.com/45317320/48972061-521ca080-f05e-11e8-948a-10e1f98f3e53.jpg)

Chip Sync Ok but different error message: **READ REG ERROR**

Again... flashing my ESP32 is FAILED.

![2018-11-25_02-52-03](https://user-images.githubusercontent.com/45317320/48972072-885a2000-f05e-11e8-8341-13435f89479a.jpg)

Please help, **how to install the Ka-Radio32 to ESP32 board?**

Any help very appreciated and thanks in advance.

**Comment by nano111** [comment]
Maybe you have wrong flash size,try 4Mbit.Try esp flash tool v3.6.2,your is 2.3

**Comment by karawin** [comment]
Yes, try a v3.6 tool.
I never had to press boot, but if you want to use it, press and hold Boot, the press Rst and release boot.

**Comment by wieb18** [comment]
> Maybe you have wrong flash size,try 4Mbit.Try esp flash tool v3.6.2,your is 2.3

Thank you for the guidance.

Using Flash Download Tool v3.6.5 download from [here](https://www.espressif.com/en/support/download/other-tools?keys=&field_type_tid%5B%5D=13)

![2018-11-25_19-01-01](https://user-images.githubusercontent.com/45317320/48978862-580d9280-f0ed-11e8-97ab-3c81d218ff3e.jpg)

Now I am able flashing ESP32 without any issue and without pressing any button.

But what I should do next?

Scanning wifi network, WifiKaRadio SSID is not found. 

ESP32 Serial output:

![2018-11-25_20-00-49](https://user-images.githubusercontent.com/45317320/48978896-03b6e280-f0ee-11e8-8fbe-cf9c6f2a9ca8.jpg)

Please help....

**Comment by nano111** [comment]
Try to erase flash first.It worked for me once.

**Comment by wieb18** [comment]
> When i see the serial, the r device is not flashed.
> Power off the esp32.
> Power on.
> Flash it with a higher speed 921600 or up.
> When finish on the tool, launch the serial
> Reboot the esp32

![2018-11-25_21-27-30](https://user-images.githubusercontent.com/45317320/48979717-dbcd7c00-f0f9-11e8-802b-35af300cc950.jpg)

![2018-11-25_21-18-53](https://user-images.githubusercontent.com/45317320/48979719-e12ac680-f0f9-11e8-9c48-77dd1e0859c7.jpg)

**Can't go higher than 921600**

![2018-11-25_21-28-43](https://user-images.githubusercontent.com/45317320/48979722-eee04c00-f0f9-11e8-9b94-ee7cf65d7317.jpg)

![2018-11-25_21-28-53](https://user-images.githubusercontent.com/45317320/48979724-f56ec380-f0f9-11e8-9a80-22d512bb2704.jpg)

**Max speed is 921600**

> Try to erase flash first.It worked for me once.

Here is what just I did:
1. Erase flash
2. Power off then power on
3. Flashing with ESP Download Tool v3.6.5. (speed 921600)
4. Power off then power on

Then... **nothing happen**

Nothing on Serial Monitor and still no WifiKaRadio SSID.

Also nothing happen on Serial Monitor when press BOOT button.

But when I press RESET button, the Serial Monitor showing this:

![2018-11-25_21-33-42](https://user-images.githubusercontent.com/45317320/48979787-a07f7d00-f0fa-11e8-8d30-2b13dcc8be5d.jpg)

Don't know what it means. Please help....

**Comment by karawin** [comment]
So, it started but crashed.
the KaRadio32.bin is the default one or do you changed something in the gpio.h before generating it?
Many errors come from a wrong configuration.
Do you wired the vs1053?
If yes, it may be not well wired. Try without it.


A good start is
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:3580
load:0x40078000,len:9300
load:0x40080400,len:5764
entry 0x400806d4
I (119) main: starting app_main()
I (119) main: RAM left: 160852
E (119) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (159) main: Partition init done...
Log level is now ESP_LOG_ERROR
E (4249) vs1053: VS1053/VS1003 detected. MP3Status: 40, Version: 4
device: 3ffcd384
I2S Speed: 0
volume: 112
E (4569) main: LCD Type 194
X: 320, yy: 240, y: 23
WIFI TRYING TO CONNECT TO SSID 1
E (5519) wifi: esp_wifi_disconnect 954 wifi not start
E (7169) event: invalid static ip
E (7169) main: 
Wifi connected

**Comment by wieb18** [comment]
> So, it started but crashed.
> the KaRadio32.bin is the default one or do you changed something in the gpio.h before generating it?
>
I am directly flashing Ka-Radio to ESP32 with ready made BIN files, so I don't have any chance to change anything. Also I am very very new to Arduino (just a few days), still don't have any clue to change anything.

> Do you wired the vs1053?
> If yes, it may be not well wired. Try without it.
> 

You are correct, the ESP32 wired to VS1053. Although VS1053 in power off condition but because the wires still attached between VS1053 and ESP32 making Ka-Radio crash. After removing all the wires, Ka-Radio finally running.

![2018-11-25_22-40-57](https://user-images.githubusercontent.com/45317320/48980497-ca3da180-f104-11e8-8039-4727ca5e2628.jpg)

Serial Monitor output:

![2018-11-25_22-53-27](https://user-images.githubusercontent.com/45317320/48980507-f6f1b900-f104-11e8-8dee-371753068d8f.jpg)

And here is my wiring between ESP32 and VS1053:

![2018-11-25_15-38-59](https://user-images.githubusercontent.com/45317320/48980512-14268780-f105-11e8-9e0a-c47ff7296539.jpg)


**My questions:**
1. Is my wiring above already correct?
2. How to connect Ka-Radio to my Wifi network? Where I put SSID and password of my own Wifi?

Thanks a lot for the help, very appreciated.

**Comment by karawin** [comment]
No, your scheme is for another project under arduino.
Here:
#define PIN_NUM_XCS  GPIO_NUM_32
#define PIN_NUM_RST  GPIO_NUM_12 
#define PIN_NUM_XDCS GPIO_NUM_33
#define PIN_NUM_DREQ GPIO_NUM_34

That explain the problem.
Your web page is not loaded. correctly.

**Comment by wieb18** [comment]
> Your web page is not loaded. correctly.

Yes, on the first run the web page took forever to load, its very slow. But after power off then power on the ESP32, it load fast (without any wires attached between ESP32 &  VS1053).

![2018-11-25_23-51-43](https://user-images.githubusercontent.com/45317320/48983310-2239cf80-f128-11e8-9871-7098fea6f80f.jpg)

Successfully changed my wifi preference on Setting Web Page.

![2018-11-25_23-52-37](https://user-images.githubusercontent.com/45317320/48983333-63ca7a80-f128-11e8-9870-a18f21875ffc.jpg)

> No, your scheme is for another project under arduino.

Thanks for the guidance, updated my wiring into this:
1. SCK to GPIO 18
2. MISO to GPIO 19
3. MOSI to GPIO 23
4. XRESET to GPIO 12
5. XDCS to GPIO 33
6. XCS to GPIO 32
7. DREG to GPIO 34

Then power off and on the ESP32 also power on VS1053.

But the result, Ka-Radio web page not able to load.

![2018-11-26_02-59-13](https://user-images.githubusercontent.com/45317320/48983544-100d6080-f12b-11e8-9ea6-39c5dda5c8f2.jpg)

Pressing RESET button on ESP32, the Serial Monitor displaying this message:
```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:3580
load:0x40078000,len:9300
load:0x40080400,len:5764
entry 0x400806d4
I (118) main: starting app_main()
I (118) main: RAM left: 160852
E (118) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (158) main: Partition init done...
Log level is now ESP_LOG_ERROR
E (4188) vs1053: VS1053/VS1003 detected. MP3Status: 0, Version: 0
device: 3ffcd384
volume: 162
E (4288) main: LCD Type 0
X: 128, YY: 64, Y: 9
WIFI TRYING TO CONNECT TO SSID 1
E (5778) wifi: esp_wifi_disconnect 954 wifi not start
E (7128) event: invalid static ip
E (7128) main: 
Wifi connected

DNS: 192.168.0.230  
IP: 192.168.0.240

gpio_get_button0 error 4354
gpio_get_button1 error 4354
gpio_get_adc error 4354
E (13558) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (13558) task_wdt:  - IDLE0 (CPU 0)
E (13558) task_wdt: Tasks currently running:
E (13558) task_wdt: CPU 0: task_lcd
E (13558) task_wdt: CPU 1: IDLE1
E (18548) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (18548) task_wdt:  - IDLE0 (CPU 0)
E (18548) task_wdt: Tasks currently running:
E (18548) task_wdt: CPU 0: esp_timer
E (18548) task_wdt: CPU 1: IDLE1

```
As could see on Serial Monitor, now **VS1053/VS1003 detected**.

But why Ka-Radio web page very slow and I am not hear any sound from VS1053?
Is my wiring wrong again? 

Please help....

**Comment by karawin** [comment]
Something wrong in the vs1053

Detected because DREQ line comes low. Ok, but the registers are not read.
Check again.
And this is blocking so other symptoms.
Other strange thing
gpio_get_button0 error 4354
gpio_get_button1 error 4354
gpio_get_adc error 4354
It seems that the standard_adb.bin is not up to date.



[standard_adb.zip](https://github.com/karawin/Ka-Radio32/files/2613450/standard_adb.zip)

**Comment by wieb18** [comment]
>
> It seems that the standard_adb.bin is not up to date.
>

![2018-11-26_05-58-45](https://user-images.githubusercontent.com/45317320/48985305-0ee72e00-f141-11e8-87be-a94349a43898.jpg)

Strange... I got the standard_adb.bin and all the KA-Radio BIN files from your Github page. Maybe you also need updating the standard_adb.bin on KaRadio32sup.zip file to prevent anyone has the same issue like me.

Once again I do erasing and flashing my ESP32 with the new standard_adb.bin including all the BIN files then double check my wiring between ESP32 and VS1053.

![2018-11-26_05-52-06](https://user-images.githubusercontent.com/45317320/48985354-77360f80-f141-11e8-8be4-1d2a49fe9565.jpg)

Finally... VS1053 detected by KA-Radio. But why the **volume has negative value**?

Serial Monitor output:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:3580
load:0x40078000,len:9300
load:0x40080400,len:5764
entry 0x400806d4
I (118) main: starting app_main()
I (118) main: RAM left: 160852
E (118) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (158) main: Partition init done...
Log level is now ESP_LOG_ERROR
E (4198) vs1053: VS1053/VS1003 detected. MP3Status: 40, Version: 4
device: 3ffcd384
I2S Speed: 0
volume: 158
E (4518) main: LCD Type 0
X: 128, YY: 64, Y: 9
WIFI TRYING TO CONNECT TO SSID 1
E (6008) wifi: esp_wifi_disconnect 954 wifi not start
E (7338) event: invalid static ip
E (7338) main: 
Wifi connected

DNS: 192.168.0.230  
IP: 192.168.0.240

Init .......... Done
READY. Type help for a list of commands
##CLI.NAMESET#: 0 Europe1
##CLI.URLSET#: e1-live-mp3-128.scdn.arkena.com
##CLI.PATHSET#: /europe1.mp3
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 14
##CLI.VOL#: 158
##CLI.PLAYING#

##CLI.NAMESET#: 10 FIP Rock
##CLI.URLSET#: www.listenlive.eu
##CLI.PATHSET#: /fr_fiprock.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 158
##CLI.URLSET#: direct.fipradio.fr
##CLI.PATHSET#: /live/fip-webradio1.mp3?ID=f9fbk29m84
##CLI.PORTSET#: 80
##CLI.STOPPED# from C_PLIST
##CLI.STOPPED# from C_HDER
##CLI.URLSET#: chai5she.cdn.dvmr.fr
##CLI.PATHSET#: /fip-webradio1.mp3?ID=f9fbk29m84
##CLI.PORTSET#: 80
##CLI.PLAYING#

##CLI.NAMESET#: 10 FIP Rock
##CLI.URLSET#: www.listenlive.eu
##CLI.PATHSET#: /fr_fiprock.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 158
##CLI.URLSET#: direct.fipradio.fr
##CLI.PATHSET#: /live/fip-webradio1.mp3?ID=f9fbk29m84
##CLI.PORTSET#: 80
##CLI.STOPPED# from C_PLIST
##CLI.STOPPED# from C_HDER
##CLI.URLSET#: chai5she.cdn.dvmr.fr
##CLI.PATHSET#: /fip-webradio1.mp3?ID=f9fbk29m84
##CLI.PORTSET#: 80
##CLI.PLAYING#

##CLI.NAMESET#: 34 MusicOnly FM
##CLI.URLSET#: listen.radionomy.com
##CLI.PATHSET#: /musiconly-fm
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 158
##CLI.STOPPED# from C_HDER
##CLI.URLSET#: streaming.radionomy.com
##CLI.PATHSET#: /MusicOnly-FM
##CLI.PORTSET#: 80
E (126848) webclient: Client socket: 63  read: -1  errno:11 
##CLI.STOPPED# from No Data
##CLI.ICY0#: No Data
##CLI.NAMESET#: 30 Nostalgie
##CLI.URLSET#: www.listenlive.eu
##CLI.PATHSET#: /fr_nostalgie.m3u
##CLI.PORTSET#: 80
##CLI.OVOLSET#: 0
##CLI.VOL#: 158
##CLI.URLSET#: cdn.nrjaudio.fm
##CLI.PATHSET#: /audio1/fr/30601/mp3_128.mp3?origine=listenlive
##CLI.PORTSET#: 80
##CLI.STOPPED# from C_PLIST
##CLI.STOPPED# from C_HDER
##CLI.URLSET#: 185.52.127.160
##CLI.PATHSET#: /fr/30601/mp3_128.mp3?origine=listenlive
##CLI.PORTSET#: 80
##CLI.PLAYING#

CORRUPT HEAP: multi_heap.c:429 detected at 0x3ffeda78
abort() was called at PC 0x400907ff on core 0

Backtrace: 0x40090e9e:0x3ffd6d70 0x400910b9:0x3ffd6d90 0x400907ff:0x3ffd6db0 0x40082ac5:0x3ffd6dd0 0x40082af1:0x3ffd6df0 0x40082efd:0x3ffd6e10 0x400830c9:0x3ffd6e50 0x400865ad:0x3ffd6e70 0x4012b607:0x3ffd6e90 0x401356c1:0x3ffd6ed0 0x40089929:0x3ffd6f50 0x4008ed5d:0x3ffd6f90

Entering gdb stub now.
$T0b#e6

```

The radio sound is very choppy and after a few minutes KA-Radio crash.

Please guide me... where I done wrong?

**Comment by wieb18** [comment]
After the crashed above, I pressed RESET button and here is the Serial Monitor output:

![2018-11-26_06-18-31](https://user-images.githubusercontent.com/45317320/48985573-cc732080-f143-11e8-902c-f6c643ca9edc.jpg)

The ESP32 not run Wifi and Ka-Radio but directly entering Task Watchdog.

Pressing again RESET button and here is the result:

![2018-11-26_06-26-03](https://user-images.githubusercontent.com/45317320/48985613-42778780-f144-11e8-93d0-6057f73c56a1.jpg)

Now ESP32 connected to Wifi and able to run Ka-Radio (with choppy sound). But only for a few second and then crash again entering Task WatchDog loop.

What is Task WatchDog?

**Comment by karawin** [comment]
Volume is negative because it is an attenuation. Full volume is 0 decibel

How do you connected the power lines and ground?

**Comment by karawin** [comment]
There eratic logs are typical of a power problem.

**Comment by wieb18** [comment]
> 
> Volume is negative because it is an attenuation. Full volume is 0 decibel
> 

Thank you for the explanation.

> 
> How do you connected the power lines and ground?
>

The ESP32 power by 5V micro USB from PC and VS1053 power by 5V separate power supply 2Amp

**Comment by karawin** [comment]
And ground of each connected together?

**Comment by karawin** [comment]
I use to connect the 5v of the vs1053 board with the 5V of the esp32, and gnd obviouslly. No external power supply.

**Comment by wieb18** [comment]
> And ground of each connected together?

No....

I am following the wiring according Ka-Radio Github page:

```
// KSPI pins of the SPI bus
//-------------------------
#define PIN_NUM_MISO GPIO_NUM_19 	// Master Input, Slave Output
#define PIN_NUM_MOSI GPIO_NUM_23	// Master Output, Slave Input   Named Data or SDA or D1 for oled
#define PIN_NUM_CLK  GPIO_NUM_18 	// Master clock  Named SCL or SCK or D0 for oled


// gpio of the vs1053
//-------------------
#define PIN_NUM_XCS  GPIO_NUM_32
#define PIN_NUM_RST  GPIO_NUM_12 
#define PIN_NUM_XDCS GPIO_NUM_33
#define PIN_NUM_DREQ GPIO_NUM_34
// + KSPI pins

```

**Comment by wieb18** [comment]
> I use to connect the 5v of the vs1053 board with the 5V of the esp32, and gnd obviouslly. No external power supply.

I will try your guidance ASAP, hope it will solve the issue

**Comment by karawin** [comment]
It will.Every electronic equipment need a common gnd (apart audio amplifier but it is a particular case)

**Comment by wieb18** [comment]
Tried using only 1 power source for both ESP32 & VS1053:
1. Using only 5V micro USB powering from PC
2. Using only 5V 2Amp external power source 

Both result Ka-Radio works well (no crash as previously) and the sound also very good, no choppy sound anymore. 

Thanks a lot for guiding me all this time, you are the best

**Comment by karawin** [comment]
As i told you before, it is NOT an arduino project. It uses directly the esp-idf.
Start in the main directory app_main.c
The code is a multi tasks under freertos.
Sorry, no init, no loop ;-)

I am happy to see that all is resolved.
I will close the issue because it is solved.
Bye
