### ISSUE TITLE
A long time for opening the homepage in the browser

### ISSUE THREAD

**Issue by bazooka07** [karawin/Ka-Radio32#71]
Opening the homepage in the browser takes a long time because the browser sends a lot of requests for getting information for each station, one by one, with the path **getStation** and **idgp** as parameter with **post** method .

Can we have an additionnal command, for example with the path **getAllStations** without parameter, and download  all the stations, in one shot, in csv format with the charater tab as field separator, and without empty record (station without url) ?

**Comment by karawin** [comment]
This is done only one time for a new ip.
