### ISSUE TITLE
Problem with ./nvs_partition_generator.sh

### ISSUE THREAD

**Issue by RustKaz** [karawin/Ka-Radio32#76]
I beg you to help with compiling the script  ./nvs_partition_generator.sh. It goes like this:
 ./nvs_partition_generator.sh standard_adb
python C:/msys32/home/rgaysin/esp/esp-idf/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py standard_adb.csv build/standard_adb.bin 0x2000
usage: nvs_partition_gen.py [-h] [--input INPUT] [--output OUTPUT]
                            [--size SIZE] [--version {v1,v2}]
                            [--keygen {true,false}] [--encrypt {true,false}]
                            [--keyfile KEYFILE]
nvs_partition_gen.py: error: unrecognized arguments: standard_adb.csv build/standard_adb.bin 0x2000
done
The same with the script alt_nvs_partition_generator.sh.
 The script **make partition_table** -  works.   Versions: IDF - v3.3-beta1-4-g23b6d40c5, Python 2.7.15
Or just compile, please, the configuration: rust.csv.
[rust.zip](https://github.com/karawin/Ka-Radio32/files/2679887/rust.zip)
Thank you very much in advance! The project is super !!!

**Comment by karawin** [comment]
I changed the boards shell. Now the tool is local.
Please try again.
cd boards
./nvs_partition_generator.sh standard_adb

**Comment by karawin** [comment]
make partition_table  must be done only in the KaRadio32 directory with the right partitions.csv
Only usefull if you modify the code of KaRadio32 but the hardware csv is enough.
It gives

$ make partition_table
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a5
Compiler version: 5.2.0
Python requirements from C:/msys32/home/jp/esp/esp-idf/requirements.txt are satisfied.
Partition table binary generated. Contents:
*******************************************************************************
# Espressif ESP32 Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,16K,
otadata,data,ota,0xd000,8K,
phy_init,data,phy,0xf000,4K,
ota_0,app,ota_0,0x10000,1792K,
ota_1,app,ota_1,0x1d0000,1792K,
device,64,0,0x390000,4K,
stations,65,0,0x391000,64K,
device1,66,0,0x3a1000,4K,
hardware,data,nvs,0x3a2000,8K,
*******************************************************************************
Partition flashing command:
python /home/jp/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port com5 --baud 460800 --before default_reset --after hard_reset write_flash 0x8000 /home/jp/esp/Ka-Radio32/build/partitions.bin
