### ISSUE TITLE
Uncorrect i2c init

### ISSUE THREAD

**Issue by pilnikov** [karawin/Ka-Radio32#78]
If I start a new, never configurable device, on default device starts with display type #0 (LCD_I2C_SH1106), therefore, when starting, i2c bus initialization is also necessary. All OK! But .... If I plan to use a non-I2C display (for example, SPI or without a display), I set the i2c parameters in .csv as 255 (not to use) and get a startup error. It is necessary to set the values for the i2c pins other than 255.

**Comment by karawin** [comment]
Right?
I will correct it
Thanks

**Comment by karawin** [comment]
New R3 delivered
Happy new year 2019.
