### ISSUE TITLE
ODROID-GO Board support

### ISSUE THREAD

**Issue by pepelnyy** [karawin/Ka-Radio32#85]
[How-to](https://github.com/pepelnyy/KaRadio32-on-ODROID-GO)
csv and .bin
[boards.zip](https://github.com/karawin/Ka-Radio32/files/2768954/boards.zip)

**Comment by karawin** [comment]
It is not an issue. I will advertise on the readme.

**Comment by pepelnyy** [comment]
Sorry, I was wrong.

пт, 18 янв. 2019, 12:11 KaraWin notifications@github.com:
