### ISSUE TITLE
ssd1331 

### ISSUE THREAD

**Issue by hopla123** [karawin/Ka-Radio32#9]
Hi,
I have issue with rotated text by display SSD1331 (looks like 90 degree rotation), can you help me? 
Regards
Jan
![image](https://user-images.githubusercontent.com/34009602/33365781-997b51a6-d4e9-11e7-8416-6dd9b7f2cbf9.png)

**Comment by karawin** [comment]
I will see this point soon.

**Comment by karawin** [comment]
Do an OTA update and tell me if you need a 180° rotation.

**Comment by hopla123** [comment]
Thank you about help, now is rotation ok, only some additional text is not fully in display size.
![image](https://user-images.githubusercontent.com/34009602/33806966-04bb6034-ddd0-11e7-9ad8-ab713a959af0.png)

**Comment by karawin** [comment]
Yes i have to adjust for this small screen.
Wait ;-)

**Comment by karawin** [comment]
Try again.... now

**Comment by hopla123** [comment]
Hi, 
now is text inside lcd but text fonts looks as cut of.
Regards
Jan
![sd1331_karadio](https://user-images.githubusercontent.com/34009602/33845245-18102538-dea3-11e7-8255-fc302195269d.jpg)

**Comment by karawin** [comment]
again... test it aftezr ota

**Comment by hopla123** [comment]
ok, now looks fine, only startup menu is too large.
![image](https://user-images.githubusercontent.com/34009602/33854287-7626e832-dec1-11e7-8733-38f8f28ed0da.png)
![20171211_222603](https://user-images.githubusercontent.com/34009602/33854809-49608e64-dec3-11e7-905a-dd97f7efe584.jpg)
