### ISSUE TITLE
Problems with 1.8R1

### ISSUE THREAD

**Issue by Asxetos21** [karawin/Ka-Radio32#93]
Update to 1.8R1 from the web interface causes loss of IR control, LCD corruption and finally freezing.
Esp32 dev board (15+15 pin version) VS1053, ST7735, rotary enc. and IR.
Haven't tested it any further...

Going back to 1.8R0, all OK again.

**Comment by karawin** [comment]
No reason.
Try again

**Comment by Elbskipper** [comment]
Same issue with 1.8R1. Display is often corrupted after Power Up (just snow). Chip: ST7735,  128x160 .
With older versions it was always OK. Config: Esp32 dev board, VS1053, Rotary, ST7735.

**Comment by karawin** [comment]
Check with sys.lcd command the type of lcd.

**Comment by Elbskipper** [comment]
This was the first thing I did. I even changed to another display type and back without success. The strange thing is, that it sometimes works. The web interface is always ok, even if the display has failed.Am 10.02.2019 8:23 nachm. schrieb KaraWin <notifications@github.com>:Check with sys.lcd command the type of lcd.

**Comment by karawin** [comment]
May be a conflict in the definition of gpio in the csv file (check carefully if it is your definitions or which one do you use?) or a problem of sequencing in the init.
I don't have the problem so it is hard to find.

**Comment by Elbskipper** [comment]
I am using your preconfigured binary’s.
 
I will recheck the wiring and maybe I will reprogram the entire system. I somehow got the feeling (sorry for this word) that an issue was introduced, when you modified the display binary’s, I think it was in one of the updates of the 1.7 release.

**Comment by karawin** [comment]
Which csv if any please? Or the bare KaRadio32 bin only

**Comment by Elbskipper** [comment]
Just the bare KaRadio32.bin. No individual compilations. After the flashing I set the display to type “192”. 
 
In the meantime I re-flashed the entire system via the ESP32 Download Tool. I couldn`t reproduce the issue since. It looks like something went wrong during one of the OTA updates.

**Comment by Elbskipper** [comment]
I`ve repowered the System at least 20 times since the re-flash. No more display issues. So I consider this issue as fixed.

**Comment by karawin** [comment]
ok, closed
