### ISSUE TITLE
Build from source help.

### ISSUE THREAD

**Issue by Asxetos21** [karawin/Ka-Radio32#97]
I am trying to troubleshoot my display.

I have an ST7735 chinese clone (probably with an ILI9163 or S6D02A1 driver, but 128x160 res.), so the code most likely needs a bit of modification for it to work perfectly.
The problem is, i tried a few builds from source on 1.8 and 1.9 versions and even though compilation goes ok, the result does not boot.

Funny thing, ready made binaries V1.8R0 work fine (lcd declared as an ST7735 #192). 
Any version above 1.8R0 results in a corrupted display (just snow-noise). Everything else works as it should.
Changing the lcd to #195 #200 or #201 works on all versions, but of course with only part of the lcd (128x128 or 80x160, NOT 128x160) is initialized.

My setup-wiring is OK, as v1.8R0 fully work (lcd, rotary-enc, IR, vs1053), and all versions above that "sort of work" if the lcd is declared as #195 #200 or #201. 

Was there a change on the lcd code above 1.8R0?
Shouldn't the code result in a working binary "as is" on github?

**Comment by karawin** [comment]
No needs to build the binary. Take it in the binaries directory.
Once started, on serial or telnet type
sys.lcd("192")

In case of 'snow' check for an inversion of wires ;-)

**Comment by Asxetos21** [comment]
Tests for all lcd changes (see above) are done via telnet. I don't change the csv every time.

Forgive my ignorance, but if there was a case of inverted wiring, then v1.8R0 would show the same symptoms, wouldn't it? 
Plus the "intentional" wrong resolution settings (#195 #200 #201) would again not work at all, but they do.
My logic says something changed in code that simply revealed my lcd's "incompatibility" after 1.8R0.
I wouldn't mind at all staying on this version, if my rotary encoder was working trouble-free (see issue #95 "rotary encoder").
Damn those cheap chinese products...

**Comment by karawin** [comment]
- The problem is that the color driver is unchanged and type  200  201 and 202 are new type created by me and are derived from the 192 type ( the one I use everyday)  
- 200 and 201 just changed the resolution, 202: added a shift to the display for some hardware lcd.

**Comment by Asxetos21** [comment]
I tried an arduino project first, before i saw that your KaRadio is by far superior.

Having similar problems of course with my lcd, i fixed them by defining the ILI9163 as lcd type (always on ST7735 driver) and manually setting the resolution as 128x160 instead of 128x128 in code, and this worked fine.

The problem here is that i can't test any modifications (since the compiled source doesn't work).

Perhaps lcd type #203 would be possible? (ST7735 driver, ILI9163 type with 128x160 res).
I am sure there will be other victims of the chinese ingenuity...

Anyway, Thanks...

**Comment by karawin** [comment]
Looking at the github history, i cannot find a modification to explain the pb. Only some fonts are changed.
Why the compiled code doesn't work? I call ./generate.sh to compile all and it' ok.
May be a total erase before flashing may help.
I cannot change  the driver for ILI9163 because it is the same as the ST7735 but with a shift of 32 pixels.
Yes the specifications are the same or very close.

**Comment by karawin** [comment]
I (493) main: LCD Type 192
I (523) addonucg: lcd init  type: 192, Rotat: 0
I (573) ucg_hal: UCG_COM_MSG_POWER_UP: 80 ns so in Hz: 12500000
I (573) ucg_hal: ... Adding spi lcd bus  Speed= 25000000.
I (693) addonucg: lcd init Color type: 192
I (753) addonucg: X: 160, yy: 128, y: 10

**Comment by Asxetos21** [comment]
This is the console output with your pre-made  binaries flashed (full erase before).
-------------------------------------------------------------------
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:3564
load:0x40078000,len:9372
ho 0 tail 12 room 4
load:0x40080400,len:5848
entry 0x400806d8
E (478) spiram: SPI RAM enabled but initialization failed. Bailing out.
I (42) main: starting app_main()
I (42) main: RAM left: 200496
E (42) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (42) main: Partition init done...
E (42) main: Device config not ok. Try to restore
E (82) main: Device config not cleared. Clear it.
#erase All done##
#erase All done##
#erase All done##
#erase All done##
#erase All done##
#erase All done##
V (262) addon: LINE: #erase All done##

D (262) eeprom: saveDeviceSettings
Log level is now ESP_LOG_ERROR
WIFI GO TO AP MODE
E (4882) main: The default AP is  WifiKaRadio. Connect your wifi to it.
Then connect a webbrowser to 192.168.4.1 and go to Setting
May be long to load the first time.Be patient.
E (5342) main: mDNS Hostname: karadio32
READY. Type help for a list of commands
----------------------------------------------------------------------

And this is with a binary compiled from your source (again full erase)
----------------------------------------------------------------------
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:3564
load:0x40078000,len:9372
ho 0 tail 12 room 4
load:0x40080400,len:5848
entry 0x400806d8
E (468) spiram: SPI RAM enabled but initialization failed. Bailing out.
I (32) main: starting app_main()
I (32) main: RAM left: 144392
E (32) main: Running partition type 0 subtype 16 (offset 0x00010000)
I (62) main: Partition init done...
E (62) main: Device config not ok. Try to restore
E (102) main: Device config not cleared. Clear it.
#erase All done##
#erase All done##
#erase All done##
#erase All done##
#erase All done##
#erase All done##
V (282) addon: LINE: #erase All done##

D (282) eeprom: saveDeviceSettings
Log level is now ESP_LOG_ERROR
-------------------------------------------------------------------

Obviously wifi is not started.

An obvious indication that something is NOT OK, is that the resulting binary is always approx. 30-35 KB smaller than yours. 1428 vs 1393 KB for latest version.
As you, i call ./generate.sh and there is no error at all.

**Comment by karawin** [comment]
May depend on the esp-idf version.
With the very last gihub files?
I made a make clean and ./generae.sh
The size remains the same.

Strange Wifi not started, but why?
Try to type 
sys.logi and reset.

**Comment by Asxetos21** [comment]
esp-idf is suggested version (3.1.2)

sys.logi output...
---------------------------------------------------------------
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:3564
load:0x40078000,len:9372
ho 0 tail 12 room 4
load:0x40080400,len:5848
entry 0x400806d8
E (468) spiram: SPI RAM enabled but initialization failed. Bailing out.
I (32) main: starting app_main()
I (32) main: RAM left: 144392
E (32) main: Running partition type 0 subtype 16 (offset 0x00010000)
ESP_ERROR_CHECK failed: esp_err_t 0x1110 (ESP_ERR_NVS_NEW_VERSION_FOUND) at 0x400d87ba
file: "D:/msys32/home/NG/esp/Ka-Radio32/main/app_main.c" line 816
func: app_main
expression: err

Backtrace: 0x400942f6:0x3ffd2ae0 0x40094800:0x3ffd2b00 0x400d87ba:0x3ffd2b20 0x400d2f1e:0x3ffd2b60

Entering gdb stub now.
$T0b#e6
----------------------------------------------------------------------------------------

**Comment by Asxetos21** [comment]
I think you should take a look at those,
When project config is force restarted, it asks about some undefined settings mostly about bluetooth (i accept the defaults) and this is the result.
sdkconfig original, and new.

[Ka-Radio32.zip](https://github.com/karawin/Ka-Radio32/files/2892540/Ka-Radio32.zip)

**Comment by pilnikov** [comment]
E (32) main: Running partition type 0 subtype 16 (offset 0x00010000)
but must be 
..../partition.bin   start at address 0x8000
maybe you should first overwrite all .bin files via flash dowload tool? to the "correct" addresses

**Comment by Asxetos21** [comment]
It’s exactly the same if I flash a set of the premade binaries…

**Comment by pilnikov** [comment]
clean all flash (write a blank.bin 4M) or push "erase" button on flash download tool before you upload your binaries

**Comment by Asxetos21** [comment]
I erase every time just in case. It's not that...

**Comment by karawin** [comment]
New nvs . You need to generate partitions.bin.
I am qtoll on the old one. I will made it soon.

**Comment by pilnikov** [comment]
try of my .bin files
JP, why is it working out for me? new IDF?
[191_my.zip](https://github.com/karawin/Ka-Radio32/files/2893453/191_my.zip)

**Comment by Asxetos21** [comment]
@karawin 
I have generated a new partitions.bin from the beginning

@pilnikov 
Your files boot fine (erase before flash). Wifi goes to AP mode.
BUT, same result for me, just snow on #192 lcd.

This is the lcd i have.

![st7735r ebay-2](https://user-images.githubusercontent.com/25814859/53237792-444bdb00-36a0-11e9-8420-6f479ba063e1.jpg)

![st7735r ebay-3](https://user-images.githubusercontent.com/25814859/53237829-5b8ac880-36a0-11e9-892f-4c0823af1d4a.jpg)

Changing to a small i2c oled everything is super.

My question remains. Why compiled code does not work on my end.

**Comment by karawin** [comment]
https://blogs.yahoo.co.jp/hobbyele/64882532.html
https://www.youtube.com/watch?v=r_ja3jSCr5I

Concerning partitions, i am a bit lost because i don't have time to see where the problem is.

**Comment by pilnikov** [comment]
I decided to try with my ttgo ts. This esp32 with screen based on led spi ST7735. https://github.com/LilyGO/TTGO-TS-V1.2 I first programmed it in Karadio in version 1.3 (probably, it was a long time ago). I entered the web interface and clicked update. After the reboot, the display turned white. The log was similar to yours. Stop before starting wifi. I could not switch to logi for details. Instead, I ran msys and uploaded the compiled stock version 1.9R1. After that, my system started up, but the display was still not working. Then I collected .csv At first I tried with the display type 192 - The display was working for me, but the picture was shifted. It helped sys. lcd ("202"), although 200 and 201 also worked but not correctly. Maybe you have errors in .csv?
In the archive .csv .bin and schematic for TTGO TS
![p_20190222_220755](https://user-images.githubusercontent.com/25922873/53259627-5d30ac80-36f1-11e9-8c82-7ce86ab69cdf.jpg)
![p_20190222_220835](https://user-images.githubusercontent.com/25922873/53259628-5d30ac80-36f1-11e9-8186-fd46a64df600.jpg)

[ttgots.zip](https://github.com/karawin/Ka-Radio32/files/2895077/ttgots.zip)

**Comment by pilnikov** [comment]
JP can you add ttgo ts files? from my archive.

**Comment by Asxetos21** [comment]
If you agree, please close this issue, it has consumed enough time both of me and you.
It is not worth the trouble, the lcd costs 8-10 euros so i can afford to just bin it.
I will switch to the oled for now, and i have an ILI9341 with touch coming in a couple of days, so I'll work with that instead.

The software most certainly works fine. It's that crap lcd that's giving me a headache.

Thanks for the help guys...

**Comment by karawin** [comment]
Ok I close.
bye

**Comment by Asxetos21** [comment]
Your docs indicate that to build, you must clone branch v3.1.2 of the esp-idf. Following that, building from source does not boot.
Would be better to indicate that you should build with v3.3-beta1 (or even master) of the esp-idf. Changing to that, things start to work.

I spent a few wasted hours till I realized it (no error on compilation).

**Comment by karawin** [comment]
I can't see any reason of the not start of the wifi in 3.1.2
This part of the document is wrote  by a contributor and I never tested with 3.1.2 recently.
The document is mainly made to compile the csv file, not to build the project from the source.
Sorry.
